export type ShopItem = {
  key: string;
  name: string;
  description: string;
  price: number;
  premium?: boolean;
};

export type PlayerDef = ShopItem & {
  player_type: string;
  player_bg: "solid" | "glass" | "transparent";
  player_position?: string;
  preview: string;
};

/** Reproductores de música (theme.player_type + theme.player_bg) */
export const SHOP_PLAYERS: PlayerDef[] = [
  {
    key: "player-default",
    name: "Classic",
    description: "Reproductor estándar con carátula y controles.",
    price: 0,
    player_type: "default",
    player_bg: "glass",
    preview: "linear-gradient(140deg,#2b1d4d,#0b0b12)",
  },
  {
    key: "player-minimal",
    name: "Minimal",
    description: "Solo play/pausa y barra fina. Ultra discreto.",
    price: 0,
    player_type: "minimal",
    player_bg: "transparent",
    preview: "linear-gradient(140deg,#1a1a24,#0b0b12)",
  },
  {
    key: "player-structured",
    name: "Structured",
    description: "Carátula grande, título, artista y progreso detallado.",
    price: 250,
    premium: true,
    player_type: "structured",
    player_bg: "solid",
    preview: "linear-gradient(140deg,#3a1d4d,#0b0b12)",
  },
  {
    key: "player-text",
    name: "Marquee Text",
    description: "Título en marquesina animada, sin carátula.",
    price: 250,
    premium: true,
    player_type: "text",
    player_bg: "transparent",
    preview: "linear-gradient(140deg,#123,#0b0b12)",
  },
  {
    key: "player-vinyl",
    name: "Vinyl",
    description: "Carátula circular giratoria estilo tocadiscos.",
    price: 300,
    premium: true,
    player_type: "vinyl",
    player_bg: "glass",
    preview: "linear-gradient(140deg,#4d2b1d,#0b0b12)",
  },
  {
    key: "player-wave",
    name: "Waveform",
    description: "Barras de espectro animadas al ritmo de la canción.",
    price: 350,
    premium: true,
    player_type: "wave",
    player_bg: "transparent",
    preview: "linear-gradient(140deg,#1d4d47,#0b0b12)",
  },
  {
    key: "player-cassette",
    name: "Cassette",
    description: "Estética retro de cinta con bobinas en movimiento.",
    price: 400,
    premium: true,
    player_type: "cassette",
    player_bg: "solid",
    preview: "linear-gradient(140deg,#4d3d1d,#0b0b12)",
  },
  {
    key: "player-dock",
    name: "Floating Dock",
    description: "Barra flotante inferior con controles completos.",
    price: 200,
    player_type: "dock",
    player_bg: "glass",
    player_position: "bottom-center",
    preview: "linear-gradient(140deg,#1d2b4d,#0b0b12)",
  },
  {
    key: "player-corner",
    name: "Corner Pill",
    description: "Píldora compacta anclada arriba a la derecha.",
    price: 150,
    player_type: "minimal",
    player_bg: "glass",
    player_position: "top-right",
    preview: "linear-gradient(140deg,#2b4d1d,#0b0b12)",
  },
  {
    key: "player-neon",
    name: "Neon Deck",
    description: "Panel con glow de neón y progreso luminoso.",
    price: 450,
    premium: true,
    player_type: "structured",
    player_bg: "glass",
    preview: "linear-gradient(140deg,#4d1d5e,#0b0b12)",
  },
  {
    key: "player-orbit",
    name: "Orbit",
    description: "Botón circular con anillo de progreso orbitando.",
    price: 300,
    player_type: "orbit",
    player_bg: "transparent",
    preview: "linear-gradient(140deg,#1d3a4d,#0b0b12)",
  },
  {
    key: "player-poster",
    name: "Poster",
    description: "Carátula gigante de fondo con degradado y controles encima.",
    price: 500,
    premium: true,
    player_type: "poster",
    player_bg: "solid",
    preview: "linear-gradient(140deg,#5e1d3a,#0b0b12)",
  },
  {
    key: "player-lcd",
    name: "LCD Retro",
    description: "Pantalla verde estilo walkman con tipografía mono.",
    price: 350,
    player_type: "lcd",
    player_bg: "solid",
    preview: "linear-gradient(140deg,#123d24,#0b0b12)",
  },
  {
    key: "player-spectrum",
    name: "Spectrum",
    description: "Carátula con espectro vertical animado al costado.",
    price: 400,
    premium: true,
    player_type: "spectrum",
    player_bg: "glass",
    preview: "linear-gradient(140deg,#1d1d5e,#0b0b12)",
  },
  {
    key: "player-capsule",
    name: "Capsule",
    description: "Cápsula mínima con carátula redonda y progreso fino.",
    price: 200,
    player_type: "capsule",
    player_bg: "glass",
    preview: "linear-gradient(140deg,#3a3a1d,#0b0b12)",
  },
  {
    key: "player-terminal",
    name: "Terminal",
    description: "Consola con prompt, ASCII y barra de carga.",
    price: 350,
    player_type: "terminal",
    player_bg: "solid",
    preview: "linear-gradient(140deg,#0d2b0d,#0b0b12)",
  },
  {
    key: "player-hologram",
    name: "Hologram",
    description: "Panel translúcido con scanlines y glow holográfico.",
    price: 550,
    premium: true,
    player_type: "hologram",
    player_bg: "glass",
    preview: "linear-gradient(140deg,#0ea5e9,#7c3aed,#0b0b12)",
  },
];

export type LayoutDef = ShopItem & {
  template: string;
  profile_width: "compact" | "normal" | "wide";
  avatar_shape: "circle" | "rounded" | "square" | "hexagon";
  card_bg_type?: "solid" | "gradient" | "image" | "video" | "transparent";
  show_card?: boolean;
  preview: string;
};

/** Layouts personalizados (theme.template + ajustes) */
export const SHOP_LAYOUTS: LayoutDef[] = [
  {
    key: "layout-glass",
    name: "Glass",
    description: "El clásico QSY: tarjeta de cristal centrada.",
    price: 0,
    template: "glass",
    profile_width: "normal",
    avatar_shape: "circle",
    card_bg_type: "solid",
    show_card: true,
    preview: "linear-gradient(140deg,#2b1d4d,#0b0b12)",
  },
  {
    key: "layout-compact",
    name: "Pocket",
    description: "Tarjeta compacta, ideal para pocos enlaces.",
    price: 150,
    template: "glass",
    profile_width: "compact",
    avatar_shape: "rounded",
    card_bg_type: "solid",
    show_card: true,
    preview: "linear-gradient(140deg,#123,#0b0b12)",
  },
  {
    key: "layout-wide",
    name: "Widescreen",
    description: "Tarjeta ancha en dos columnas para muchos enlaces.",
    price: 300,
    premium: true,
    template: "glass",
    profile_width: "wide",
    avatar_shape: "square",
    card_bg_type: "solid",
    show_card: true,
    preview: "linear-gradient(140deg,#4d1d3a,#0b0b12)",
  },
  {
    key: "layout-hex",
    name: "Hexa Neon",
    description: "Avatar hexagonal y bordes neón sci-fi.",
    price: 400,
    premium: true,
    template: "neon",
    profile_width: "normal",
    avatar_shape: "hexagon",
    card_bg_type: "solid",
    show_card: true,
    preview: "linear-gradient(140deg,#0f4d4d,#0b0b12)",
  },
  {
    key: "layout-floating",
    name: "Floating",
    description: "Sin recuadro: el contenido flota sobre el fondo.",
    price: 0,
    template: "glass",
    profile_width: "normal",
    avatar_shape: "circle",
    card_bg_type: "transparent",
    show_card: false,
    preview: "linear-gradient(140deg,#101018,#0b0b12)",
  },
  {
    key: "layout-aurora",
    name: "Aurora",
    description: "Fondo de tarjeta en degradado violeta luminoso.",
    price: 250,
    template: "aurora",
    profile_width: "normal",
    avatar_shape: "circle",
    card_bg_type: "gradient",
    show_card: true,
    preview: "linear-gradient(140deg,#6d28d9,#1e1b4b,#0b0b12)",
  },
  {
    key: "layout-terminal",
    name: "Terminal",
    description: "Estilo consola: bordes duros y tipografía mono.",
    price: 300,
    template: "terminal",
    profile_width: "compact",
    avatar_shape: "square",
    card_bg_type: "solid",
    show_card: true,
    preview: "linear-gradient(140deg,#0f2417,#0b0b12)",
  },
  {
    key: "layout-cinema",
    name: "Cinema",
    description: "Tarjeta ancha pensada para fondos de video.",
    price: 450,
    premium: true,
    template: "cinema",
    profile_width: "wide",
    avatar_shape: "rounded",
    card_bg_type: "video",
    show_card: true,
    preview: "linear-gradient(140deg,#1b1b2f,#3a0d3a,#0b0b12)",
  },
  {
    key: "layout-sakura",
    name: "Sakura",
    description: "Rosado suave con bordes redondeados y glow cálido.",
    price: 350,
    template: "sakura",
    profile_width: "normal",
    avatar_shape: "circle",
    card_bg_type: "gradient",
    show_card: true,
    preview: "linear-gradient(140deg,#f472b6,#4c1d95,#0b0b12)",
  },
  {
    key: "layout-brutal",
    name: "Brutalist",
    description: "Bloques sólidos, cero blur y contraste extremo.",
    price: 300,
    template: "brutal",
    profile_width: "compact",
    avatar_shape: "square",
    card_bg_type: "solid",
    show_card: true,
    preview: "linear-gradient(140deg,#2b2b2b,#0b0b12)",
  },
  {
    key: "layout-holo",
    name: "Holographic",
    description: "Reflejos iridiscentes y borde cromado animado.",
    price: 500,
    premium: true,
    template: "holo",
    profile_width: "normal",
    avatar_shape: "hexagon",
    card_bg_type: "gradient",
    show_card: true,
    preview: "linear-gradient(140deg,#22d3ee,#a855f7,#0b0b12)",
  },
  {
    key: "layout-poster",
    name: "Poster",
    description: "Banner gigante arriba con avatar superpuesto XL.",
    price: 400,
    premium: true,
    template: "poster",
    profile_width: "wide",
    avatar_shape: "rounded",
    card_bg_type: "image",
    show_card: true,
    preview: "linear-gradient(140deg,#4d1d1d,#0b0b12)",
  },
  {
    key: "layout-noir",
    name: "Noir",
    description: "Blanco y negro, sin glow. Elegancia mínima.",
    price: 0,
    template: "minimal",
    profile_width: "compact",
    avatar_shape: "circle",
    card_bg_type: "solid",
    show_card: true,
    preview: "linear-gradient(140deg,#1c1c1c,#050505)",
  },
  {
    key: "layout-stack",
    name: "Stack",
    description: "Enlaces apilados a ancho completo sobre el fondo.",
    price: 0,
    template: "dark",
    profile_width: "normal",
    avatar_shape: "rounded",
    card_bg_type: "transparent",
    show_card: false,
    preview: "linear-gradient(140deg,#161622,#0b0b12)",
  },
  {
    key: "layout-vapor",
    name: "Vaporwave",
    description: "Degradado rosa/cian con retícula retro de los 90.",
    price: 250,
    template: "vapor",
    profile_width: "normal",
    avatar_shape: "square",
    card_bg_type: "gradient",
    show_card: true,
    preview: "linear-gradient(140deg,#ff6ec7,#22d3ee,#0b0b12)",
  },
  {
    key: "layout-arcade",
    name: "Arcade",
    description: "Píxeles, bordes duros y paleta de recreativa.",
    price: 300,
    template: "arcade",
    profile_width: "compact",
    avatar_shape: "square",
    card_bg_type: "solid",
    show_card: true,
    preview: "linear-gradient(140deg,#1d1d4d,#7c1d4d,#0b0b12)",
  },
  {
    key: "layout-ivory",
    name: "Ivory",
    description: "Tarjeta clara y cálida para perfiles editoriales.",
    price: 200,
    template: "ivory",
    profile_width: "normal",
    avatar_shape: "rounded",
    card_bg_type: "gradient",
    show_card: true,
    preview: "linear-gradient(140deg,#f5efe6,#8b7f70,#0b0b12)",
  },
  {
    key: "layout-nebula",
    name: "Nebula",
    description: "Nebulosa animada dentro de la tarjeta, avatar hexagonal.",
    price: 450,
    premium: true,
    template: "nebula",
    profile_width: "wide",
    avatar_shape: "hexagon",
    card_bg_type: "gradient",
    show_card: true,
    preview: "linear-gradient(140deg,#5b21b6,#0ea5e9,#0b0b12)",
  },
  {
    key: "layout-y2k",
    name: "Y2K",
    description: "Cromo líquido, brillos y estética 2000s.",
    price: 500,
    premium: true,
    template: "y2k",
    profile_width: "normal",
    avatar_shape: "circle",
    card_bg_type: "gradient",
    show_card: true,
    preview: "linear-gradient(140deg,#c0c9ff,#f0abfc,#0b0b12)",
  },
  {
    key: "layout-mono",
    name: "Monolith",
    description: "Bloque oscuro a ancho completo, cero adornos.",
    price: 0,
    template: "dark",
    profile_width: "wide",
    avatar_shape: "square",
    card_bg_type: "solid",
    show_card: true,
    preview: "linear-gradient(140deg,#141418,#050505)",
  },
  {
    key: "layout-bubble",
    name: "Bubble",
    description: "Esquinas ultra redondeadas y aire entre bloques.",
    price: 200,
    template: "glass",
    profile_width: "compact",
    avatar_shape: "circle",
    card_bg_type: "gradient",
    show_card: true,
    preview: "linear-gradient(140deg,#8b5cf6,#22d3ee,#0b0b12)",
  },
  {
    key: "layout-magazine",
    name: "Magazine",
    description: "Portada editorial con banner e imagen de fondo.",
    price: 350,
    template: "poster",
    profile_width: "wide",
    avatar_shape: "rounded",
    card_bg_type: "image",
    show_card: true,
    preview: "linear-gradient(140deg,#c2410c,#1c1917,#0b0b12)",
  },
  {
    key: "layout-neonoir",
    name: "Neo Noir",
    description: "Monocromo con un único acento de neón.",
    price: 300,
    template: "minimal",
    profile_width: "normal",
    avatar_shape: "circle",
    card_bg_type: "gradient",
    show_card: true,
    preview: "linear-gradient(140deg,#0b0b12,#e11d48)",
  },
  {
    key: "layout-frost",
    name: "Frostbite",
    description: "Cristal helado azul con bordes escarchados.",
    price: 250,
    template: "glass",
    profile_width: "normal",
    avatar_shape: "rounded",
    card_bg_type: "gradient",
    show_card: true,
    preview: "linear-gradient(140deg,#bae6fd,#1e3a8a,#0b0b12)",
  },
  {
    key: "layout-solar",
    name: "Solaris",
    description: "Corona solar animada detrás de un avatar hexagonal.",
    price: 450,
    premium: true,
    template: "aurora",
    profile_width: "wide",
    avatar_shape: "hexagon",
    card_bg_type: "gradient",
    show_card: true,
    preview: "linear-gradient(140deg,#f59e0b,#7c2d12,#0b0b12)",
  },
];

/** Estilos para el nombre de usuario (theme.username_effect) */
export type NameStyleDef = ShopItem & { effect: string };

export const SHOP_NAME_STYLES: NameStyleDef[] = [
  { key: "name-none", name: "Normal", description: "Sin efecto, el nombre limpio.", price: 0, effect: "none" },
  { key: "name-glow", name: "Glow", description: "Resplandor suave con tu color de acento.", price: 0, effect: "glow" },
  { key: "name-gradient", name: "Gradient", description: "Degradado del acento al blanco.", price: 0, effect: "gradient" },
  { key: "name-outline", name: "Outline", description: "Solo contorno, relleno transparente.", price: 0, effect: "outline" },
  { key: "name-shine", name: "Shine", description: "Barrido de luz que recorre las letras.", price: 150, effect: "shine" },
  { key: "name-rainbow", name: "Rainbow", description: "Arcoíris animado en bucle infinito.", price: 250, effect: "rainbow" },
  { key: "name-glitch", name: "Glitch", description: "Desfase RGB estilo error de señal.", price: 300, effect: "glitch" },
  { key: "name-neon", name: "Neon Sign", description: "Tubo de neón con parpadeo eléctrico.", price: 350, effect: "neon" },
  { key: "name-typewriter", name: "Typewriter", description: "Cursor parpadeante estilo terminal.", price: 200, effect: "typewriter" },
  { key: "name-chrome", name: "Chrome", description: "Metal líquido con reflejos cromados.", price: 400, premium: true, effect: "chrome" },
  { key: "name-fire", name: "Inferno", description: "Degradado ardiente con brillo naranja.", price: 450, premium: true, effect: "fire" },
  { key: "name-ice", name: "Frost", description: "Hielo azul con destellos fríos.", price: 400, premium: true, effect: "ice" },
  { key: "name-sparkle", name: "Sparkle", description: "Purpurina animada sobre las letras.", price: 500, premium: true, effect: "sparkle" },
  { key: "name-gold", name: "Gold", description: "Oro pulido con barrido de luz.", price: 400, effect: "gold" },
  { key: "name-toxic", name: "Toxic", description: "Verde radiactivo con glow ácido.", price: 250, effect: "toxic" },
  { key: "name-aqua", name: "Aqua", description: "Degradado cian a violeta en movimiento.", price: 200, effect: "aqua" },
  { key: "name-candy", name: "Candy", description: "Rayas de caramelo animadas.", price: 250, effect: "candy" },
  { key: "name-holo", name: "Holo", description: "Iridiscencia holográfica pastel.", price: 450, premium: true, effect: "holo" },
  { key: "name-shadow3d", name: "3D Shadow", description: "Sombra sólida en capas con profundidad.", price: 200, effect: "shadow3d" },
  { key: "name-heartbeat", name: "Heartbeat", description: "Latido rítmico con halo de acento.", price: 300, effect: "heartbeat" },
  { key: "name-wave", name: "Wave", description: "Flotación vertical continua.", price: 150, effect: "wave" },
  { key: "name-terminal", name: "Terminal", description: "Verde fósforo estilo consola.", price: 200, effect: "terminal" },
  { key: "name-blurpulse", name: "Blur Pulse", description: "Desenfoque pulsante hipnótico.", price: 300, effect: "blurpulse" },
  { key: "name-galaxy", name: "Galaxy", description: "Nebulosa estrellada dentro de las letras.", price: 500, premium: true, effect: "galaxy" },
  { key: "name-strobe", name: "Strobe", description: "Cambio de tono estroboscópico.", price: 350, premium: true, effect: "strobe" },
  { key: "name-emboss", name: "Emboss", description: "Relieve grabado sobre la tarjeta.", price: 0, effect: "emboss" },
  { key: "name-lavender", name: "Lavender", description: "Degradado lavanda suave y constante.", price: 150, effect: "lavender" },
  { key: "name-bounce", name: "Bounce", description: "Rebote alegre letra a letra.", price: 150, effect: "bounce" },
  { key: "name-sunset", name: "Sunset", description: "Atardecer naranja a violeta en movimiento.", price: 200, effect: "sunset" },
  { key: "name-pixel", name: "Pixel", description: "Sombra dura de 8 bits estilo arcade.", price: 200, effect: "pixel" },
  { key: "name-matrix", name: "Matrix", description: "Verde código con parpadeo digital.", price: 250, effect: "matrix" },
  { key: "name-static", name: "Static", description: "Interferencia analógica constante.", price: 250, effect: "static" },
  { key: "name-plasma", name: "Plasma", description: "Plasma violeta y cian en mutación.", price: 300, effect: "plasma" },
  { key: "name-blood", name: "Blood", description: "Rojo profundo con goteo luminoso.", price: 350, effect: "blood" },
  { key: "name-oil", name: "Oil Slick", description: "Aceite iridiscente en movimiento lento.", price: 450, premium: true, effect: "oil" },
];

/** Efectos animados de fondo (theme.bg_effect) */
export type BgEffectDef = ShopItem & { effect: string; preview: string };

export const SHOP_BG_EFFECTS: BgEffectDef[] = [
  { key: "bg-none", name: "Ninguno", description: "Fondo limpio, sin capas animadas.", price: 0, effect: "none", preview: "linear-gradient(140deg,#111,#0b0b12)" },
  { key: "bg-stars", name: "Estrellas", description: "Campo de estrellas con parpadeo lento.", price: 0, effect: "stars", preview: "linear-gradient(140deg,#0b1030,#0b0b12)" },
  { key: "bg-aurora", name: "Aurora", description: "Cortinas de luz violeta en movimiento.", price: 0, effect: "aurora", preview: "linear-gradient(140deg,#4c1d95,#0e7490,#0b0b12)" },
  { key: "bg-night", name: "Noche", description: "Viñeta profunda con niebla azulada.", price: 0, effect: "night", preview: "linear-gradient(140deg,#0b1a2b,#0b0b12)" },
  { key: "bg-rain", name: "Lluvia", description: "Gotas cayendo en diagonal.", price: 150, effect: "rain", preview: "linear-gradient(140deg,#1b2b3a,#0b0b12)" },
  { key: "bg-snow", name: "Nieve", description: "Copos flotando suavemente.", price: 150, effect: "snow", preview: "linear-gradient(140deg,#243447,#0b0b12)" },
  { key: "bg-bubbles", name: "Burbujas", description: "Burbujas ascendentes translúcidas.", price: 200, effect: "bubbles", preview: "linear-gradient(140deg,#0f3d4d,#0b0b12)" },
  { key: "bg-confetti", name: "Confetti", description: "Confeti multicolor en caída constante.", price: 200, effect: "confetti", preview: "linear-gradient(140deg,#4d1d3a,#0b0b12)" },
  { key: "bg-fireflies", name: "Luciérnagas", description: "Puntos cálidos flotando en la oscuridad.", price: 250, effect: "fireflies", preview: "linear-gradient(140deg,#1d2b12,#0b0b12)" },
  { key: "bg-matrix", name: "Matrix", description: "Lluvia de código verde.", price: 300, effect: "matrix", preview: "linear-gradient(140deg,#052b16,#0b0b12)" },
  { key: "bg-oldtv", name: "Old TV", description: "Scanlines y ruido de tubo catódico.", price: 300, effect: "oldtv", preview: "linear-gradient(140deg,#2b2b2b,#0b0b12)" },
  { key: "bg-grid", name: "Retro Grid", description: "Retícula infinita con horizonte neón.", price: 350, effect: "grid", preview: "linear-gradient(140deg,#3b0d5e,#0b0b12)" },
  { key: "bg-plasma", name: "Plasma", description: "Manchas de plasma en mutación continua.", price: 450, premium: true, effect: "plasma", preview: "linear-gradient(140deg,#7c1d6f,#1d4d7c,#0b0b12)" },
  { key: "bg-dither", name: "Dither", description: "Trama de puntos animada estilo retro.", price: 400, premium: true, effect: "dither", preview: "linear-gradient(140deg,#333,#0b0b12)" },
  { key: "bg-nebula", name: "Nebulosa", description: "Nube estelar en rotación permanente.", price: 500, premium: true, effect: "nebula", preview: "linear-gradient(140deg,#4338ca,#a21caf,#0b0b12)" },
  { key: "bg-sakura", name: "Sakura", description: "Pétalos de cerezo cayendo suavemente.", price: 250, effect: "sakura", preview: "linear-gradient(140deg,#f472b6,#4c1d95,#0b0b12)" },
  { key: "bg-hearts", name: "Corazones", description: "Corazones flotando hacia arriba.", price: 200, effect: "hearts", preview: "linear-gradient(140deg,#7c1d3a,#0b0b12)" },
  { key: "bg-embers", name: "Brasas", description: "Chispas ardientes subiendo en la oscuridad.", price: 300, effect: "embers", preview: "linear-gradient(140deg,#7c3a1d,#0b0b12)" },
  { key: "bg-clouds", name: "Nubes", description: "Nubes lentas en movimiento continuo.", price: 150, effect: "clouds", preview: "linear-gradient(140deg,#2b3a4d,#0b0b12)" },
  { key: "bg-vortex", name: "Vórtice", description: "Espiral cónica girando con tu color de acento.", price: 400, effect: "vortex", preview: "linear-gradient(140deg,#3a1d7c,#0b0b12)" },
  { key: "bg-cyberrain", name: "Cyber Rain", description: "Lluvia de neón cian y violeta.", price: 350, effect: "cyberrain", preview: "linear-gradient(140deg,#0e4d5e,#3a1d7c,#0b0b12)" },
  { key: "bg-spotlight", name: "Spotlight", description: "Foco cenital que respira sobre el perfil.", price: 200, effect: "spotlight", preview: "linear-gradient(140deg,#2b2b3d,#0b0b12)" },
  { key: "bg-lava", name: "Lava", description: "Resplandor volcánico en la parte inferior.", price: 400, premium: true, effect: "lava", preview: "linear-gradient(140deg,#7c1d0d,#0b0b12)" },
  { key: "bg-smoke", name: "Humo", description: "Volutas de humo etéreo desplazándose.", price: 300, effect: "smoke", preview: "linear-gradient(140deg,#3a3a44,#0b0b12)" },
  { key: "bg-fireworks", name: "Fuegos artificiales", description: "Destellos de colores estallando en bucle.", price: 500, premium: true, effect: "fireworks", preview: "linear-gradient(140deg,#7c1d6f,#1d4d7c,#0b0b12)" },
  { key: "bg-stardust", name: "Polvo estelar", description: "Partículas finas flotando sin parar.", price: 0, effect: "stardust", preview: "linear-gradient(140deg,#1b1b3a,#0b0b12)" },
  { key: "bg-orbs", name: "Orbes", description: "Esferas de luz flotando en profundidad.", price: 200, effect: "orbs", preview: "linear-gradient(140deg,#3a1d7c,#0e7490,#0b0b12)" },
  { key: "bg-ripple", name: "Ondas", description: "Ondas concéntricas que se expanden.", price: 200, effect: "ripple", preview: "linear-gradient(140deg,#0e4d5e,#0b0b12)" },
  { key: "bg-waves", name: "Marea", description: "Olas suaves desplazándose en bucle.", price: 250, effect: "waves", preview: "linear-gradient(140deg,#0f766e,#0b0b12)" },
  { key: "bg-meteors", name: "Meteoros", description: "Estrellas fugaces cruzando la pantalla.", price: 300, effect: "meteors", preview: "linear-gradient(140deg,#1e1b4b,#0b0b12)" },
  { key: "bg-circuit", name: "Circuito", description: "Placa de circuito con pulsos de energía.", price: 350, effect: "circuit", preview: "linear-gradient(140deg,#052b2b,#0b0b12)" },
  { key: "bg-glitch", name: "Glitch", description: "Bandas de error digital intermitentes.", price: 400, premium: true, effect: "glitch", preview: "linear-gradient(140deg,#7c1d6f,#0ea5e9,#0b0b12)" },
  { key: "bg-caustics", name: "Cáusticas", description: "Reflejos de agua proyectados en la escena.", price: 450, premium: true, effect: "caustics", preview: "linear-gradient(140deg,#0891b2,#1e3a8a,#0b0b12)" },
];

/** Animaciones al pasar el ratón sobre la tarjeta del biolink (theme.hover_effect) */
export type HoverEffectDef = ShopItem & { effect: string; preview: string };

export const SHOP_HOVER_EFFECTS: HoverEffectDef[] = [
  { key: "hover-none", name: "Ninguna", description: "Sin animación al pasar el ratón.", price: 0, effect: "none", preview: "linear-gradient(140deg,#111,#0b0b12)" },
  { key: "hover-lift", name: "Lift", description: "La tarjeta se eleva con una sombra suave.", price: 0, effect: "lift", preview: "linear-gradient(140deg,#1c1c28,#0b0b12)" },
  { key: "hover-zoom", name: "Zoom", description: "Acercamiento sutil de todo el layout.", price: 200, effect: "zoom", preview: "linear-gradient(140deg,#123,#0b0b12)" },
  { key: "hover-tilt", name: "Tilt 3D", description: "Inclinación en perspectiva estilo 3D.", price: 200, effect: "tilt", preview: "linear-gradient(140deg,#2b1d4d,#0b0b12)" },
  { key: "hover-glow", name: "Neon Glow", description: "Halo de neón con tu color de acento.", price: 250, effect: "glow", preview: "linear-gradient(140deg,#3b0d5e,#0b0b12)" },
  { key: "hover-float", name: "Float", description: "Flotación continua mientras apuntas.", price: 300, effect: "float", preview: "linear-gradient(140deg,#0f3d4d,#0b0b12)" },
  { key: "hover-shine", name: "Shine", description: "Destello diagonal que recorre la tarjeta.", price: 300, premium: true, effect: "shine", preview: "linear-gradient(140deg,#4d1d3a,#0b0b12)" },
  { key: "hover-jelly", name: "Jelly", description: "Rebote elástico al entrar el cursor.", price: 350, premium: true, effect: "jelly", preview: "linear-gradient(140deg,#1d2b12,#0b0b12)" },
  { key: "hover-rgb", name: "RGB Border", description: "Borde arcoíris girando sin parar.", price: 400, premium: true, effect: "rgb", preview: "linear-gradient(140deg,#7c1d6f,#1d4d7c,#0b0b12)" },
  { key: "hover-scan", name: "Scanline", description: "Línea de escaneo cyberpunk de arriba abajo.", price: 450, premium: true, effect: "scan", preview: "linear-gradient(140deg,#052b16,#0b0b12)" },
  { key: "hover-pop", name: "Pop", description: "Escala y elevación marcada al apuntar.", price: 150, effect: "pop", preview: "linear-gradient(140deg,#1d2b4d,#0b0b12)" },
  { key: "hover-swing", name: "Swing", description: "Balanceo suave de la tarjeta.", price: 200, effect: "swing", preview: "linear-gradient(140deg,#4d3d1d,#0b0b12)" },
  { key: "hover-wobble", name: "Wobble", description: "Sacudida lateral divertida.", price: 250, effect: "wobble", preview: "linear-gradient(140deg,#4d1d1d,#0b0b12)" },
  { key: "hover-blur", name: "Focus", description: "El perfil está desenfocado y se enfoca al apuntar.", price: 300, effect: "blur", preview: "linear-gradient(140deg,#2b2b3d,#0b0b12)" },
  { key: "hover-breathe", name: "Breathe", description: "Respiración lenta con halo pulsante.", price: 350, effect: "breathe", preview: "linear-gradient(140deg,#1d4d3a,#0b0b12)" },
  { key: "hover-skew", name: "Skew", description: "Inclinación diagonal editorial.", price: 250, effect: "skew", preview: "linear-gradient(140deg,#3d1d4d,#0b0b12)" },
  { key: "hover-flip", name: "Flip 3D", description: "Giro en perspectiva sobre el eje Y.", price: 400, premium: true, effect: "flip", preview: "linear-gradient(140deg,#1d3d5e,#0b0b12)" },
  { key: "hover-hologram", name: "Hologram", description: "Scanlines holográficas recorriendo la tarjeta.", price: 500, premium: true, effect: "hologram", preview: "linear-gradient(140deg,#0ea5e9,#7c3aed,#0b0b12)" },
  { key: "hover-neonpulse", name: "Neon Pulse", description: "Borde de neón latiendo sin parar.", price: 450, premium: true, effect: "neonpulse", preview: "linear-gradient(140deg,#7c1d6f,#0b0b12)" },
];

/** Decoraciones de avatar estilo Discord (theme.avatar_decoration) */
export type DecorationDef = ShopItem & { image: string | null };

export const SHOP_DECORATIONS: DecorationDef[] = [
  {
    key: "none",
    name: "Sin decoración",
    description: "Avatar limpio, sin marco.",
    price: 0,
    image: null,
  },
  {
    key: "pink-bunny",
    name: "Pink Bunny",
    description: "Decoración de avatar Pink Bunny.",
    price: 0,
    image: "https://o.keta.rip/decorations/frame-1781737464562/1781737464562-55366440177b1d86.png",
  },
  {
    key: "cat-ears",
    name: "Cat Ears",
    description: "Decoración de avatar Cat Ears.",
    price: 0,
    image: "https://o.keta.rip/decorations/frame-1781737600977/1781737600977-9cad4707a43d1f54.png",
  },
  {
    key: "enojon",
    name: "Enojon",
    description: "Decoración de avatar Enojon.",
    price: 0,
    image: "https://o.keta.rip/decorations/frame-1781737755467/1781737755468-54c7d39710221259.png",
  },
  {
    key: "rex",
    name: "Rex",
    description: "Decoración de avatar Rex.",
    price: 250,
    image: "https://o.keta.rip/decorations/frame-1783359954117/1783359954117-b8de639fd3e1faa9.png",
  },
  {
    key: "enojon-rosita",
    name: "Enojon Rosita",
    description: "Decoración de avatar Enojon Rosita.",
    price: 200,
    image: "https://o.keta.rip/decorations/frame-1782654382050/1782654382050-b1b9e0df982f39cf.png",
  },
  {
    key: "chococat",
    name: "Chococat",
    description: "Decoración de avatar Chococat.",
    price: 300,
    image: "https://o.keta.rip/decorations/frame-1782654402792/1782654402793-ddf0e69afcd360d7.png",
  },
  {
    key: "polvo-blanco",
    name: "Polvo Blanco",
    description: "Decoración de avatar Polvo Blanco.",
    price: 250,
    image: "https://o.keta.rip/decorations/frame-1782654424096/1782654424097-0e8d7f5ca066ed94.png",
  },
  {
    key: "dientes",
    name: "Dientes",
    description: "Decoración de avatar Dientes.",
    price: 200,
    image: "https://o.keta.rip/decorations/frame-1782654447694/1782654447694-b6c3b99e84de0779.png",
  },
  {
    key: "colegiala-kun",
    name: "Colegiala-kun",
    description: "Decoración de avatar Colegiala-kun.",
    price: 350,
    image: "https://o.keta.rip/decorations/frame-1782654460269/1782654460269-67da41a4d8860ba0.png",
  },
  {
    key: "brillitos",
    name: "Brillitos",
    description: "Decoración de avatar Brillitos.",
    price: 0,
    image: "https://o.keta.rip/decorations/frame-1782654516721/1782654516721-827a3a9b9fe92bd0.png",
  },
  {
    key: "alitas",
    name: "Alitas",
    description: "Decoración de avatar Alitas.",
    price: 300,
    image: "https://o.keta.rip/decorations/frame-1782654528910/1782654528910-402d5eaf661e031c.png",
  },
  {
    key: "enamorado",
    name: "Enamorado",
    description: "Decoración de avatar Enamorado.",
    price: 250,
    image: "https://o.keta.rip/decorations/frame-1782654535488/1782654535489-73d317a7a69011f9.png",
  },
  {
    key: "hello-kitty",
    name: "Hello Kitty",
    description: "Decoración de avatar Hello Kitty.",
    price: 400,
    premium: true,
    image: "https://o.keta.rip/decorations/frame-1782140719683/1782140719683-ffa133d73bc47026.png",
  },
  {
    key: "misterio",
    name: "???",
    description: "Decoración de avatar ???.",
    price: 600,
    premium: true,
    image: "https://o.keta.rip/decorations/frame-1782140867667/1782140867667-118beef15e427a5a.png",
  },
  {
    key: "skill-issue",
    name: "Skill Issue",
    description: "Decoración de avatar Skill Issue.",
    price: 300,
    image: "https://o.keta.rip/decorations/frame-1782654558837/1782654558837-7a5d4d1f1654f7fe.png",
  },
  {
    key: "cinnamon-roll",
    name: "Cinnamon Roll",
    description: "Decoración de avatar Cinnamon Roll.",
    price: 400,
    premium: true,
    image: "https://o.keta.rip/decorations/frame-1782654571452/1782654571452-7d751caf6709432f.png",
  },
  {
    key: "my-melody",
    name: "My Melody",
    description: "Decoración de avatar My Melody.",
    price: 400,
    premium: true,
    image: "https://o.keta.rip/decorations/frame-1782654577556/1782654577556-7d8c282a2ffa3c93.png",
  },
  {
    key: "fantasmita",
    name: "Fantasmita",
    description: "Decoración de avatar Fantasmita.",
    price: 350,
    image: "https://o.keta.rip/decorations/frame-1782654588792/1782654588792-bdf97979d69c0aad.png",
  },
  {
    key: "luna",
    name: "Luna",
    description: "Decoración de avatar Luna.",
    price: 500,
    premium: true,
    image: "https://o.keta.rip/decorations/frame-1782654661260/1782654661260-bf531084f81a0c61.png",
  },
  {
    key: "marcianitos",
    name: "Marcianitos",
    description: "Decoración de avatar Marcianitos.",
    price: 500,
    premium: true,
    image: "https://o.keta.rip/decorations/frame-1783359363870/1783359363870-25db32ec5b5f27da.png",
  },
  {
    key: "a-duck",
    name: "A Duck",
    description: "Decoración de avatar A Duck.",
    price: 0,
    image: "https://r2.zyo.lol/decoration/a_duck.png",
  },
  {
    key: "a-hint-of-clove",
    name: "A Hint Of Clove",
    description: "Decoración de avatar A Hint Of Clove.",
    price: 0,
    image: "https://r2.zyo.lol/decoration/a_hint_of_clove.png",
  },
  {
    key: "a-real-fungi",
    name: "A Real Fungi",
    description: "Decoración de avatar A Real Fungi.",
    price: 250,
    image: "https://r2.zyo.lol/decoration/a_real_fungi.png",
  },
  {
    key: "aim-for-love",
    name: "Aim For Love",
    description: "Decoración de avatar Aim For Love.",
    price: 350,
    image: "https://r2.zyo.lol/decoration/aim_for_love.png",
  },
  {
    key: "air",
    name: "Air",
    description: "Decoración de avatar Air.",
    price: 450,
    image: "https://r2.zyo.lol/decoration/air.png",
  },
  {
    key: "akuma",
    name: "Akuma",
    description: "Decoración de avatar Akuma.",
    price: 600,
    premium: true,
    image: "https://r2.zyo.lol/decoration/akuma.png",
  },
  {
    key: "all-might",
    name: "All Might",
    description: "Decoración de avatar All Might.",
    price: 0,
    image: "https://r2.zyo.lol/decoration/all_might.png",
  },
  {
    key: "ambient-ripples-arctic",
    name: "Ambient Ripples Arctic",
    description: "Decoración de avatar Ambient Ripples Arctic.",
    price: 0,
    image: "https://r2.zyo.lol/decoration/ambient_ripples_arctic.png",
  },
  {
    key: "ambient-ripples-bubblegum",
    name: "Ambient Ripples Bubblegum",
    description: "Decoración de avatar Ambient Ripples Bubblegum.",
    price: 250,
    image: "https://r2.zyo.lol/decoration/ambient_ripples_bubblegum.png",
  },
  {
    key: "ambient-ripples-golden",
    name: "Ambient Ripples Golden",
    description: "Decoración de avatar Ambient Ripples Golden.",
    price: 350,
    image: "https://r2.zyo.lol/decoration/ambient_ripples_golden.png",
  },
  {
    key: "ambient-ripples-lavender",
    name: "Ambient Ripples Lavender",
    description: "Decoración de avatar Ambient Ripples Lavender.",
    price: 450,
    image: "https://r2.zyo.lol/decoration/ambient_ripples_lavender.png",
  },
  {
    key: "amethyst-choker",
    name: "Amethyst Choker",
    description: "Decoración de avatar Amethyst Choker.",
    price: 600,
    premium: true,
    image: "https://r2.zyo.lol/decoration/amethyst_choker.png",
  },
  {
    key: "andys-room-clouds",
    name: "Andys Room Clouds",
    description: "Decoración de avatar Andys Room Clouds.",
    price: 0,
    image: "https://r2.zyo.lol/decoration/andys_room_clouds.png",
  },
  {
    key: "angel",
    name: "Angel",
    description: "Decoración de avatar Angel.",
    price: 0,
    image: "https://r2.zyo.lol/decoration/angel.png",
  },
  {
    key: "angel-headphones",
    name: "Angel Headphones",
    description: "Decoración de avatar Angel Headphones.",
    price: 250,
    image: "https://r2.zyo.lol/decoration/angel_headphones.png",
  },
  {
    key: "angry-yellow",
    name: "Angry Yellow",
    description: "Decoración de avatar Angry Yellow.",
    price: 600,
    premium: true,
    image: "https://r2.zyo.lol/decoration/angry_yellow.png",
  },
  {
    key: "aquarius",
    name: "Aquarius",
    description: "Decoración de avatar Aquarius.",
    price: 0,
    image: "https://r2.zyo.lol/decoration/aquarius.png",
  },
  {
    key: "arcane-sigil",
    name: "Arcane Sigil",
    description: "Decoración de avatar Arcane Sigil.",
    price: 0,
    image: "https://r2.zyo.lol/decoration/arcane_sigil.png",
  },
  {
    key: "ares-disc",
    name: "Ares Disc",
    description: "Decoración de avatar Ares Disc.",
    price: 250,
    image: "https://r2.zyo.lol/decoration/ares_disc.png",
  },
  {
    key: "aries",
    name: "Aries",
    description: "Decoración de avatar Aries.",
    price: 350,
    image: "https://r2.zyo.lol/decoration/aries.png",
  },
  {
    key: "astral-aura",
    name: "Astral Aura",
    description: "Decoración de avatar Astral Aura.",
    price: 450,
    image: "https://r2.zyo.lol/decoration/astral_aura.png",
  },
  {
    key: "astrolabe-gold",
    name: "Astrolabe Gold",
    description: "Decoración de avatar Astrolabe Gold.",
    price: 600,
    premium: true,
    image: "https://r2.zyo.lol/decoration/astrolabe_gold.png",
  },
  {
    key: "astrolabe-silver",
    name: "Astrolabe Silver",
    description: "Decoración de avatar Astrolabe Silver.",
    price: 0,
    image: "https://r2.zyo.lol/decoration/astrolabe_silver.png",
  },
  {
    key: "astronaut-helmet",
    name: "Astronaut Helmet",
    description: "Decoración de avatar Astronaut Helmet.",
    price: 0,
    image: "https://r2.zyo.lol/decoration/astronaut_helmet.png",
  },
  {
    key: "atakhans-aura-of-malice",
    name: "Atakhans Aura Of Malice",
    description: "Decoración de avatar Atakhans Aura Of Malice.",
    price: 250,
    image: "https://r2.zyo.lol/decoration/atakhans_aura_of_malice.png",
  },
  {
    key: "aurora",
    name: "Aurora",
    description: "Decoración de avatar Aurora.",
    price: 350,
    image: "https://r2.zyo.lol/decoration/aurora.png",
  },
  {
    key: "autumn-crown",
    name: "Autumn Crown",
    description: "Decoración de avatar Autumn Crown.",
    price: 450,
    image: "https://r2.zyo.lol/decoration/autumn_crown.png",
  },
  {
    key: "autumn-foliage",
    name: "Autumn Foliage",
    description: "Decoración de avatar Autumn Foliage.",
    price: 600,
    premium: true,
    image: "https://r2.zyo.lol/decoration/autumn_foliage.png",
  },
  {
    key: "autumns-arbor",
    name: "Autumns Arbor",
    description: "Decoración de avatar Autumns Arbor.",
    price: 0,
    image: "https://r2.zyo.lol/decoration/autumns_arbor.png",
  },
  {
    key: "autumns-arbor-aurora",
    name: "Autumns Arbor Aurora",
    description: "Decoración de avatar Autumns Arbor Aurora.",
    price: 0,
    image: "https://r2.zyo.lol/decoration/autumns_arbor_aurora.png",
  },
  {
    key: "azure-dice",
    name: "Azure Dice",
    description: "Decoración de avatar Azure Dice.",
    price: 250,
    image: "https://r2.zyo.lol/decoration/azure_dice.png",
  },
  {
    key: "baby-displacer-beast",
    name: "Baby Displacer Beast",
    description: "Decoración de avatar Baby Displacer Beast.",
    price: 350,
    image: "https://r2.zyo.lol/decoration/baby_displacer_beast.png",
  },
  {
    key: "baker-bear",
    name: "Baker Bear",
    description: "Decoración de avatar Baker Bear.",
    price: 450,
    image: "https://r2.zyo.lol/decoration/baker_bear.png",
  },
  {
    key: "balance",
    name: "Balance",
    description: "Decoración de avatar Balance.",
    price: 600,
    premium: true,
    image: "https://r2.zyo.lol/decoration/balance.png",
  },
  {
    key: "bananabelle",
    name: "Bananabelle",
    description: "Decoración de avatar Bananabelle.",
    price: 0,
    image: "https://r2.zyo.lol/decoration/bananabelle.png",
  },
  {
    key: "bandit-mask",
    name: "Bandit Mask",
    description: "Decoración de avatar Bandit Mask.",
    price: 0,
    image: "https://r2.zyo.lol/decoration/bandit_mask.png",
  },
  {
    key: "beach-hat",
    name: "Beach Hat",
    description: "Decoración de avatar Beach Hat.",
    price: 250,
    image: "https://r2.zyo.lol/decoration/beach_hat.png",
  },
  {
    key: "berry-bunny",
    name: "Berry Bunny",
    description: "Decoración de avatar Berry Bunny.",
    price: 350,
    image: "https://r2.zyo.lol/decoration/berry_bunny.png",
  },
  {
    key: "berry-cute",
    name: "Berry Cute",
    description: "Decoración de avatar Berry Cute.",
    price: 450,
    image: "https://r2.zyo.lol/decoration/berry_cute.png",
  },
  {
    key: "black-hole",
    name: "Black Hole",
    description: "Decoración de avatar Black Hole.",
    price: 600,
    premium: true,
    image: "https://r2.zyo.lol/decoration/black_hole.png",
  },
  {
    key: "black-mana",
    name: "Black Mana",
    description: "Decoración de avatar Black Mana.",
    price: 0,
    image: "https://r2.zyo.lol/decoration/black_mana.png",
  },
  {
    key: "blade-storm",
    name: "Blade Storm",
    description: "Decoración de avatar Blade Storm.",
    price: 0,
    image: "https://r2.zyo.lol/decoration/blade_storm.png",
  },
  {
    key: "bloodthirsty-gold",
    name: "Bloodthirsty Gold",
    description: "Decoración de avatar Bloodthirsty Gold.",
    price: 350,
    image: "https://r2.zyo.lol/decoration/bloodthirsty_gold.png",
  },
  {
    key: "bloodthirsty-green",
    name: "Bloodthirsty Green",
    description: "Decoración de avatar Bloodthirsty Green.",
    price: 450,
    image: "https://r2.zyo.lol/decoration/bloodthirsty_green.png",
  },
  {
    key: "bloomling",
    name: "Bloomling",
    description: "Decoración de avatar Bloomling.",
    price: 600,
    premium: true,
    image: "https://r2.zyo.lol/decoration/bloomling.png",
  },
];

export function decorationByKey(key?: string) {
  return SHOP_DECORATIONS.find((d) => d.key === key);
}

export function layoutByKey(key?: string) {
  return SHOP_LAYOUTS.find((l) => l.key === key);
}

export function playerByKey(key?: string) {
  return SHOP_PLAYERS.find((p) => p.key === key);
}

export function nameStyleByEffect(effect?: string) {
  return SHOP_NAME_STYLES.find((n) => n.effect === (effect ?? "none"));
}

export function hoverEffectByEffect(effect?: string) {
  return SHOP_HOVER_EFFECTS.find((h) => h.effect === (effect ?? "none"));
}

export function bgEffectByEffect(effect?: string) {
  return SHOP_BG_EFFECTS.find((b) => b.effect === (effect ?? "none"));
}

/** Un item es usable si es gratis o si el usuario lo desbloqueó. */
export function isOwned(item: ShopItem, unlocks: Iterable<string>) {
  if (item.price === 0) return true;
  for (const k of unlocks) if (k === item.key) return true;
  return false;
}

/** Diseños para los módulos de Steam / Twitch / Roblox (theme.gaming_style) */
export type GamingStyleDef = ShopItem & {
  style: string;
  preview: string;
  /** Rango mínimo requerido para equiparlo (no se compra con coins). */
  rank?: "obsidian" | "seraph";
};

export const SHOP_GAMING: GamingStyleDef[] = [
  {
    key: "gaming-classic",
    name: "Classic",
    description: "Tarjeta de cristal con el color de cada plataforma.",
    price: 0,
    style: "classic",
    preview: "linear-gradient(140deg,#1d2b4d,#0b0b12)",
  },
  {
    key: "gaming-ghost",
    name: "Ghost",
    description: "Sin fondo ni borde, solo el contenido.",
    price: 0,
    style: "ghost",
    preview: "linear-gradient(140deg,#141420,#0b0b12)",
  },
  {
    key: "gaming-outline",
    name: "Outline",
    description: "Contorno limpio del color de la plataforma.",
    price: 0,
    style: "outline",
    preview: "linear-gradient(140deg,#12232b,#0b0b12)",
  },
  {
    key: "gaming-compact",
    name: "Compact Pill",
    description: "Píldora baja y redondeada, ideal para varias cuentas.",
    price: 0,
    style: "compact",
    preview: "linear-gradient(140deg,#1d3a2b,#0b0b12)",
  },
  {
    key: "gaming-neon",
    name: "Neon",
    description: "Borde luminoso con glow del color de la plataforma.",
    price: 250,
    style: "neon",
    preview: "linear-gradient(140deg,#3b0d5e,#0b0b12)",
  },
  {
    key: "gaming-gradient",
    name: "Gradient",
    description: "Degradado diagonal teñido con el color de la marca.",
    price: 250,
    style: "gradient",
    preview: "linear-gradient(140deg,#4d1d3a,#0b0b12)",
  },
  {
    key: "gaming-glassdeep",
    name: "Deep Glass",
    description: "Cristal esmerilado intenso con borde claro.",
    price: 200,
    style: "glassdeep",
    preview: "linear-gradient(140deg,#2b2b3d,#0b0b12)",
  },
  {
    key: "gaming-lcd",
    name: "LCD",
    description: "Pantalla retro con tipografía monoespaciada.",
    price: 300,
    style: "lcd",
    preview: "linear-gradient(140deg,#123d24,#0b0b12)",
  },
  {
    key: "gaming-terminal",
    name: "Terminal",
    description: "Consola negra con borde fósforo y texto mono.",
    price: 300,
    style: "terminal",
    preview: "linear-gradient(140deg,#0d2b0d,#0b0b12)",
  },
  {
    key: "gaming-brutal",
    name: "Brutal",
    description: "Bordes duros y sombra sólida estilo brutalista.",
    price: 350,
    style: "brutal",
    preview: "linear-gradient(140deg,#3a3a1d,#0b0b12)",
  },
  {
    key: "gaming-holo",
    name: "Hologram",
    description: "Panel holográfico con scanlines y glow cian.",
    price: 0,
    premium: true,
    rank: "obsidian",
    style: "holo",
    preview: "linear-gradient(140deg,#0ea5e9,#7c3aed,#0b0b12)",
  },
  {
    key: "gaming-chrome",
    name: "Chrome",
    description: "Metal líquido con reflejos cromados.",
    price: 0,
    premium: true,
    rank: "obsidian",
    style: "chrome",
    preview: "linear-gradient(140deg,#e8e8ee,#2a2a33,#0b0b12)",
  },
  {
    key: "gaming-aurora",
    name: "Aurora",
    description: "Borde animado con cortinas de luz en movimiento.",
    price: 0,
    premium: true,
    rank: "seraph",
    style: "aurora",
    preview: "linear-gradient(140deg,#4338ca,#a21caf,#0b0b12)",
  },
  {
    key: "gaming-prism",
    name: "Prism",
    description: "Halo cónico arcoíris girando alrededor de la tarjeta.",
    price: 0,
    premium: true,
    rank: "seraph",
    style: "prism",
    preview: "conic-gradient(from 0deg,#f43f5e,#f59e0b,#22d3ee,#a855f7,#f43f5e)",
  },
];

export function gamingStyleByKey(key?: string) {
  return SHOP_GAMING.find((g) => g.key === key);
}

/** ¿El rango del usuario alcanza para este diseño de gaming? */
export function gamingRankOk(item: GamingStyleDef, rank?: string | null) {
  if (!item.rank) return true;
  const r = (rank ?? "").toLowerCase();
  if (item.rank === "obsidian") return r === "obsidian" || r === "seraph";
  return r === "seraph";
}
