/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardAdminRouteImport } from './routes/_authenticated/dashboard.admin'
import { Route as AuthenticatedDashboardAnalyticsRouteImport } from './routes/_authenticated/dashboard.analytics'
import { Route as AuthenticatedDashboardBadgesRouteImport } from './routes/_authenticated/dashboard.badges'
import { Route as AuthenticatedDashboardLinksRouteImport } from './routes/_authenticated/dashboard.links'
import { Route as AuthenticatedDashboardPremiumRouteImport } from './routes/_authenticated/dashboard.premium'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard.profile'
import { Route as AuthenticatedDashboardProfilesRouteImport } from './routes/_authenticated/dashboard.profiles'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedDashboardAdminIndexRouteImport } from './routes/_authenticated/dashboard.admin.index'
import { Route as AuthenticatedDashboardAdminChatRouteImport } from './routes/_authenticated/dashboard.admin.chat'
import { Route as AuthenticatedDashboardAdminModerationRouteImport } from './routes/_authenticated/dashboard.admin.moderation'
import { Route as AuthenticatedDashboardAdminSecurityRouteImport } from './routes/_authenticated/dashboard.admin.security'
import { Route as AuthenticatedDashboardAdminUsersRouteImport } from './routes/_authenticated/dashboard.admin.users'
import { Route as AuthenticatedDashboardProfileIndexRouteImport } from './routes/_authenticated/dashboard.profile.index'
import { Route as AuthenticatedDashboardProfileAdvancedRouteImport } from './routes/_authenticated/dashboard.profile.advanced'
import { Route as AuthenticatedDashboardProfileConnectionsRouteImport } from './routes/_authenticated/dashboard.profile.connections'
import { Route as AuthenticatedDashboardProfileCustomizationRouteImport } from './routes/_authenticated/dashboard.profile.customization'
import { Route as AuthenticatedDashboardProfileEffectsRouteImport } from './routes/_authenticated/dashboard.profile.effects'
import { Route as AuthenticatedDashboardProfileModulesRouteImport } from './routes/_authenticated/dashboard.profile.modules'
import { Route as AuthenticatedDashboardProfileShareRouteImport } from './routes/_authenticated/dashboard.profile.share'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminRoute =
  AuthenticatedDashboardAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAnalyticsRoute =
  AuthenticatedDashboardAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBadgesRoute =
  AuthenticatedDashboardBadgesRouteImport.update({
    id: '/badges',
    path: '/badges',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLinksRoute =
  AuthenticatedDashboardLinksRouteImport.update({
    id: '/links',
    path: '/links',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPremiumRoute =
  AuthenticatedDashboardPremiumRouteImport.update({
    id: '/premium',
    path: '/premium',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfilesRoute =
  AuthenticatedDashboardProfilesRouteImport.update({
    id: '/profiles',
    path: '/profiles',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminIndexRoute =
  AuthenticatedDashboardAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminChatRoute =
  AuthenticatedDashboardAdminChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminModerationRoute =
  AuthenticatedDashboardAdminModerationRouteImport.update({
    id: '/moderation',
    path: '/moderation',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminSecurityRoute =
  AuthenticatedDashboardAdminSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminUsersRoute =
  AuthenticatedDashboardAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardProfileIndexRoute =
  AuthenticatedDashboardProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardProfileRoute,
  } as any)
const AuthenticatedDashboardProfileAdvancedRoute =
  AuthenticatedDashboardProfileAdvancedRouteImport.update({
    id: '/advanced',
    path: '/advanced',
    getParentRoute: () => AuthenticatedDashboardProfileRoute,
  } as any)
const AuthenticatedDashboardProfileConnectionsRoute =
  AuthenticatedDashboardProfileConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedDashboardProfileRoute,
  } as any)
const AuthenticatedDashboardProfileCustomizationRoute =
  AuthenticatedDashboardProfileCustomizationRouteImport.update({
    id: '/customization',
    path: '/customization',
    getParentRoute: () => AuthenticatedDashboardProfileRoute,
  } as any)
const AuthenticatedDashboardProfileEffectsRoute =
  AuthenticatedDashboardProfileEffectsRouteImport.update({
    id: '/effects',
    path: '/effects',
    getParentRoute: () => AuthenticatedDashboardProfileRoute,
  } as any)
const AuthenticatedDashboardProfileModulesRoute =
  AuthenticatedDashboardProfileModulesRouteImport.update({
    id: '/modules',
    path: '/modules',
    getParentRoute: () => AuthenticatedDashboardProfileRoute,
  } as any)
const AuthenticatedDashboardProfileShareRoute =
  AuthenticatedDashboardProfileShareRouteImport.update({
    id: '/share',
    path: '/share',
    getParentRoute: () => AuthenticatedDashboardProfileRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/templates': typeof TemplatesRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRouteWithChildren
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/badges': typeof AuthenticatedDashboardBadgesRoute
  '/dashboard/links': typeof AuthenticatedDashboardLinksRoute
  '/dashboard/premium': typeof AuthenticatedDashboardPremiumRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRouteWithChildren
  '/dashboard/profiles': typeof AuthenticatedDashboardProfilesRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/admin/chat': typeof AuthenticatedDashboardAdminChatRoute
  '/dashboard/admin/moderation': typeof AuthenticatedDashboardAdminModerationRoute
  '/dashboard/admin/security': typeof AuthenticatedDashboardAdminSecurityRoute
  '/dashboard/admin/users': typeof AuthenticatedDashboardAdminUsersRoute
  '/dashboard/profile/advanced': typeof AuthenticatedDashboardProfileAdvancedRoute
  '/dashboard/profile/connections': typeof AuthenticatedDashboardProfileConnectionsRoute
  '/dashboard/profile/customization': typeof AuthenticatedDashboardProfileCustomizationRoute
  '/dashboard/profile/effects': typeof AuthenticatedDashboardProfileEffectsRoute
  '/dashboard/profile/modules': typeof AuthenticatedDashboardProfileModulesRoute
  '/dashboard/profile/share': typeof AuthenticatedDashboardProfileShareRoute
  '/dashboard/admin/': typeof AuthenticatedDashboardAdminIndexRoute
  '/dashboard/profile/': typeof AuthenticatedDashboardProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/templates': typeof TemplatesRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/badges': typeof AuthenticatedDashboardBadgesRoute
  '/dashboard/links': typeof AuthenticatedDashboardLinksRoute
  '/dashboard/premium': typeof AuthenticatedDashboardPremiumRoute
  '/dashboard/profiles': typeof AuthenticatedDashboardProfilesRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/admin/chat': typeof AuthenticatedDashboardAdminChatRoute
  '/dashboard/admin/moderation': typeof AuthenticatedDashboardAdminModerationRoute
  '/dashboard/admin/security': typeof AuthenticatedDashboardAdminSecurityRoute
  '/dashboard/admin/users': typeof AuthenticatedDashboardAdminUsersRoute
  '/dashboard/profile/advanced': typeof AuthenticatedDashboardProfileAdvancedRoute
  '/dashboard/profile/connections': typeof AuthenticatedDashboardProfileConnectionsRoute
  '/dashboard/profile/customization': typeof AuthenticatedDashboardProfileCustomizationRoute
  '/dashboard/profile/effects': typeof AuthenticatedDashboardProfileEffectsRoute
  '/dashboard/profile/modules': typeof AuthenticatedDashboardProfileModulesRoute
  '/dashboard/profile/share': typeof AuthenticatedDashboardProfileShareRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminIndexRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$username': typeof UsernameRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/templates': typeof TemplatesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/admin': typeof AuthenticatedDashboardAdminRouteWithChildren
  '/_authenticated/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/_authenticated/dashboard/badges': typeof AuthenticatedDashboardBadgesRoute
  '/_authenticated/dashboard/links': typeof AuthenticatedDashboardLinksRoute
  '/_authenticated/dashboard/premium': typeof AuthenticatedDashboardPremiumRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRouteWithChildren
  '/_authenticated/dashboard/profiles': typeof AuthenticatedDashboardProfilesRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/admin/chat': typeof AuthenticatedDashboardAdminChatRoute
  '/_authenticated/dashboard/admin/moderation': typeof AuthenticatedDashboardAdminModerationRoute
  '/_authenticated/dashboard/admin/security': typeof AuthenticatedDashboardAdminSecurityRoute
  '/_authenticated/dashboard/admin/users': typeof AuthenticatedDashboardAdminUsersRoute
  '/_authenticated/dashboard/profile/advanced': typeof AuthenticatedDashboardProfileAdvancedRoute
  '/_authenticated/dashboard/profile/connections': typeof AuthenticatedDashboardProfileConnectionsRoute
  '/_authenticated/dashboard/profile/customization': typeof AuthenticatedDashboardProfileCustomizationRoute
  '/_authenticated/dashboard/profile/effects': typeof AuthenticatedDashboardProfileEffectsRoute
  '/_authenticated/dashboard/profile/modules': typeof AuthenticatedDashboardProfileModulesRoute
  '/_authenticated/dashboard/profile/share': typeof AuthenticatedDashboardProfileShareRoute
  '/_authenticated/dashboard/admin/': typeof AuthenticatedDashboardAdminIndexRoute
  '/_authenticated/dashboard/profile/': typeof AuthenticatedDashboardProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/explore'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/templates'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/badges'
    | '/dashboard/links'
    | '/dashboard/premium'
    | '/dashboard/profile'
    | '/dashboard/profiles'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/admin/chat'
    | '/dashboard/admin/moderation'
    | '/dashboard/admin/security'
    | '/dashboard/admin/users'
    | '/dashboard/profile/advanced'
    | '/dashboard/profile/connections'
    | '/dashboard/profile/customization'
    | '/dashboard/profile/effects'
    | '/dashboard/profile/modules'
    | '/dashboard/profile/share'
    | '/dashboard/admin/'
    | '/dashboard/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$username'
    | '/explore'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/templates'
    | '/dashboard/analytics'
    | '/dashboard/badges'
    | '/dashboard/links'
    | '/dashboard/premium'
    | '/dashboard/profiles'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/admin/chat'
    | '/dashboard/admin/moderation'
    | '/dashboard/admin/security'
    | '/dashboard/admin/users'
    | '/dashboard/profile/advanced'
    | '/dashboard/profile/connections'
    | '/dashboard/profile/customization'
    | '/dashboard/profile/effects'
    | '/dashboard/profile/modules'
    | '/dashboard/profile/share'
    | '/dashboard/admin'
    | '/dashboard/profile'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$username'
    | '/explore'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/templates'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/admin'
    | '/_authenticated/dashboard/analytics'
    | '/_authenticated/dashboard/badges'
    | '/_authenticated/dashboard/links'
    | '/_authenticated/dashboard/premium'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/profiles'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/admin/chat'
    | '/_authenticated/dashboard/admin/moderation'
    | '/_authenticated/dashboard/admin/security'
    | '/_authenticated/dashboard/admin/users'
    | '/_authenticated/dashboard/profile/advanced'
    | '/_authenticated/dashboard/profile/connections'
    | '/_authenticated/dashboard/profile/customization'
    | '/_authenticated/dashboard/profile/effects'
    | '/_authenticated/dashboard/profile/modules'
    | '/_authenticated/dashboard/profile/share'
    | '/_authenticated/dashboard/admin/'
    | '/_authenticated/dashboard/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  UsernameRoute: typeof UsernameRoute
  ExploreRoute: typeof ExploreRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  TemplatesRoute: typeof TemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin': {
      id: '/_authenticated/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/analytics': {
      id: '/_authenticated/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof AuthenticatedDashboardAnalyticsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/badges': {
      id: '/_authenticated/dashboard/badges'
      path: '/badges'
      fullPath: '/dashboard/badges'
      preLoaderRoute: typeof AuthenticatedDashboardBadgesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/links': {
      id: '/_authenticated/dashboard/links'
      path: '/links'
      fullPath: '/dashboard/links'
      preLoaderRoute: typeof AuthenticatedDashboardLinksRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/premium': {
      id: '/_authenticated/dashboard/premium'
      path: '/premium'
      fullPath: '/dashboard/premium'
      preLoaderRoute: typeof AuthenticatedDashboardPremiumRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profiles': {
      id: '/_authenticated/dashboard/profiles'
      path: '/profiles'
      fullPath: '/dashboard/profiles'
      preLoaderRoute: typeof AuthenticatedDashboardProfilesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin/': {
      id: '/_authenticated/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof AuthenticatedDashboardAdminIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/chat': {
      id: '/_authenticated/dashboard/admin/chat'
      path: '/chat'
      fullPath: '/dashboard/admin/chat'
      preLoaderRoute: typeof AuthenticatedDashboardAdminChatRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/moderation': {
      id: '/_authenticated/dashboard/admin/moderation'
      path: '/moderation'
      fullPath: '/dashboard/admin/moderation'
      preLoaderRoute: typeof AuthenticatedDashboardAdminModerationRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/security': {
      id: '/_authenticated/dashboard/admin/security'
      path: '/security'
      fullPath: '/dashboard/admin/security'
      preLoaderRoute: typeof AuthenticatedDashboardAdminSecurityRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/users': {
      id: '/_authenticated/dashboard/admin/users'
      path: '/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof AuthenticatedDashboardAdminUsersRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/profile/': {
      id: '/_authenticated/dashboard/profile/'
      path: '/'
      fullPath: '/dashboard/profile/'
      preLoaderRoute: typeof AuthenticatedDashboardProfileIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardProfileRoute
    }
    '/_authenticated/dashboard/profile/advanced': {
      id: '/_authenticated/dashboard/profile/advanced'
      path: '/advanced'
      fullPath: '/dashboard/profile/advanced'
      preLoaderRoute: typeof AuthenticatedDashboardProfileAdvancedRouteImport
      parentRoute: typeof AuthenticatedDashboardProfileRoute
    }
    '/_authenticated/dashboard/profile/connections': {
      id: '/_authenticated/dashboard/profile/connections'
      path: '/connections'
      fullPath: '/dashboard/profile/connections'
      preLoaderRoute: typeof AuthenticatedDashboardProfileConnectionsRouteImport
      parentRoute: typeof AuthenticatedDashboardProfileRoute
    }
    '/_authenticated/dashboard/profile/customization': {
      id: '/_authenticated/dashboard/profile/customization'
      path: '/customization'
      fullPath: '/dashboard/profile/customization'
      preLoaderRoute: typeof AuthenticatedDashboardProfileCustomizationRouteImport
      parentRoute: typeof AuthenticatedDashboardProfileRoute
    }
    '/_authenticated/dashboard/profile/effects': {
      id: '/_authenticated/dashboard/profile/effects'
      path: '/effects'
      fullPath: '/dashboard/profile/effects'
      preLoaderRoute: typeof AuthenticatedDashboardProfileEffectsRouteImport
      parentRoute: typeof AuthenticatedDashboardProfileRoute
    }
    '/_authenticated/dashboard/profile/modules': {
      id: '/_authenticated/dashboard/profile/modules'
      path: '/modules'
      fullPath: '/dashboard/profile/modules'
      preLoaderRoute: typeof AuthenticatedDashboardProfileModulesRouteImport
      parentRoute: typeof AuthenticatedDashboardProfileRoute
    }
    '/_authenticated/dashboard/profile/share': {
      id: '/_authenticated/dashboard/profile/share'
      path: '/share'
      fullPath: '/dashboard/profile/share'
      preLoaderRoute: typeof AuthenticatedDashboardProfileShareRouteImport
      parentRoute: typeof AuthenticatedDashboardProfileRoute
    }
  }
}

interface AuthenticatedDashboardAdminRouteChildren {
  AuthenticatedDashboardAdminChatRoute: typeof AuthenticatedDashboardAdminChatRoute
  AuthenticatedDashboardAdminModerationRoute: typeof AuthenticatedDashboardAdminModerationRoute
  AuthenticatedDashboardAdminSecurityRoute: typeof AuthenticatedDashboardAdminSecurityRoute
  AuthenticatedDashboardAdminUsersRoute: typeof AuthenticatedDashboardAdminUsersRoute
  AuthenticatedDashboardAdminIndexRoute: typeof AuthenticatedDashboardAdminIndexRoute
}

const AuthenticatedDashboardAdminRouteChildren: AuthenticatedDashboardAdminRouteChildren =
  {
    AuthenticatedDashboardAdminChatRoute: AuthenticatedDashboardAdminChatRoute,
    AuthenticatedDashboardAdminModerationRoute:
      AuthenticatedDashboardAdminModerationRoute,
    AuthenticatedDashboardAdminSecurityRoute:
      AuthenticatedDashboardAdminSecurityRoute,
    AuthenticatedDashboardAdminUsersRoute:
      AuthenticatedDashboardAdminUsersRoute,
    AuthenticatedDashboardAdminIndexRoute:
      AuthenticatedDashboardAdminIndexRoute,
  }

const AuthenticatedDashboardAdminRouteWithChildren =
  AuthenticatedDashboardAdminRoute._addFileChildren(
    AuthenticatedDashboardAdminRouteChildren,
  )

interface AuthenticatedDashboardProfileRouteChildren {
  AuthenticatedDashboardProfileAdvancedRoute: typeof AuthenticatedDashboardProfileAdvancedRoute
  AuthenticatedDashboardProfileConnectionsRoute: typeof AuthenticatedDashboardProfileConnectionsRoute
  AuthenticatedDashboardProfileCustomizationRoute: typeof AuthenticatedDashboardProfileCustomizationRoute
  AuthenticatedDashboardProfileEffectsRoute: typeof AuthenticatedDashboardProfileEffectsRoute
  AuthenticatedDashboardProfileModulesRoute: typeof AuthenticatedDashboardProfileModulesRoute
  AuthenticatedDashboardProfileShareRoute: typeof AuthenticatedDashboardProfileShareRoute
  AuthenticatedDashboardProfileIndexRoute: typeof AuthenticatedDashboardProfileIndexRoute
}

const AuthenticatedDashboardProfileRouteChildren: AuthenticatedDashboardProfileRouteChildren =
  {
    AuthenticatedDashboardProfileAdvancedRoute:
      AuthenticatedDashboardProfileAdvancedRoute,
    AuthenticatedDashboardProfileConnectionsRoute:
      AuthenticatedDashboardProfileConnectionsRoute,
    AuthenticatedDashboardProfileCustomizationRoute:
      AuthenticatedDashboardProfileCustomizationRoute,
    AuthenticatedDashboardProfileEffectsRoute:
      AuthenticatedDashboardProfileEffectsRoute,
    AuthenticatedDashboardProfileModulesRoute:
      AuthenticatedDashboardProfileModulesRoute,
    AuthenticatedDashboardProfileShareRoute:
      AuthenticatedDashboardProfileShareRoute,
    AuthenticatedDashboardProfileIndexRoute:
      AuthenticatedDashboardProfileIndexRoute,
  }

const AuthenticatedDashboardProfileRouteWithChildren =
  AuthenticatedDashboardProfileRoute._addFileChildren(
    AuthenticatedDashboardProfileRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAdminRoute: typeof AuthenticatedDashboardAdminRouteWithChildren
  AuthenticatedDashboardAnalyticsRoute: typeof AuthenticatedDashboardAnalyticsRoute
  AuthenticatedDashboardBadgesRoute: typeof AuthenticatedDashboardBadgesRoute
  AuthenticatedDashboardLinksRoute: typeof AuthenticatedDashboardLinksRoute
  AuthenticatedDashboardPremiumRoute: typeof AuthenticatedDashboardPremiumRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRouteWithChildren
  AuthenticatedDashboardProfilesRoute: typeof AuthenticatedDashboardProfilesRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAdminRoute:
      AuthenticatedDashboardAdminRouteWithChildren,
    AuthenticatedDashboardAnalyticsRoute: AuthenticatedDashboardAnalyticsRoute,
    AuthenticatedDashboardBadgesRoute: AuthenticatedDashboardBadgesRoute,
    AuthenticatedDashboardLinksRoute: AuthenticatedDashboardLinksRoute,
    AuthenticatedDashboardPremiumRoute: AuthenticatedDashboardPremiumRoute,
    AuthenticatedDashboardProfileRoute:
      AuthenticatedDashboardProfileRouteWithChildren,
    AuthenticatedDashboardProfilesRoute: AuthenticatedDashboardProfilesRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  UsernameRoute: UsernameRoute,
  ExploreRoute: ExploreRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  TemplatesRoute: TemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
