/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RankRouteImport } from './routes/rank'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StatusRouteImport } from './routes/status'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardAdminRouteImport } from './routes/_authenticated/dashboard.admin'
import { Route as AuthenticatedDashboardAnalyticsRouteImport } from './routes/_authenticated/dashboard.analytics'
import { Route as AuthenticatedDashboardBadgesRouteImport } from './routes/_authenticated/dashboard.badges'
import { Route as AuthenticatedDashboardGalleryRouteImport } from './routes/_authenticated/dashboard.gallery'
import { Route as AuthenticatedDashboardGiftRouteImport } from './routes/_authenticated/dashboard.gift'
import { Route as AuthenticatedDashboardLinksRouteImport } from './routes/_authenticated/dashboard.links'
import { Route as AuthenticatedDashboardMissionsRouteImport } from './routes/_authenticated/dashboard.missions'
import { Route as AuthenticatedDashboardOgRouteImport } from './routes/_authenticated/dashboard.og'
import { Route as AuthenticatedDashboardPremiumRouteImport } from './routes/_authenticated/dashboard.premium'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard.profile'
import { Route as AuthenticatedDashboardProfilesRouteImport } from './routes/_authenticated/dashboard.profiles'
import { Route as AuthenticatedDashboardRankRouteImport } from './routes/_authenticated/dashboard.rank'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedDashboardTemplatesRouteImport } from './routes/_authenticated/dashboard.templates'
import { Route as AuthenticatedDashboardAdminIndexRouteImport } from './routes/_authenticated/dashboard.admin.index'
import { Route as AuthenticatedDashboardAdminAuditRouteImport } from './routes/_authenticated/dashboard.admin.audit'
import { Route as AuthenticatedDashboardAdminBoostsRouteImport } from './routes/_authenticated/dashboard.admin.boosts'
import { Route as AuthenticatedDashboardAdminChatRouteImport } from './routes/_authenticated/dashboard.admin.chat'
import { Route as AuthenticatedDashboardAdminContentRouteImport } from './routes/_authenticated/dashboard.admin.content'
import { Route as AuthenticatedDashboardAdminEmailsRouteImport } from './routes/_authenticated/dashboard.admin.emails'
import { Route as AuthenticatedDashboardAdminIntegrationsRouteImport } from './routes/_authenticated/dashboard.admin.integrations'
import { Route as AuthenticatedDashboardAdminIptrackerRouteImport } from './routes/_authenticated/dashboard.admin.iptracker'
import { Route as AuthenticatedDashboardAdminModerationRouteImport } from './routes/_authenticated/dashboard.admin.moderation'
import { Route as AuthenticatedDashboardAdminRanksRouteImport } from './routes/_authenticated/dashboard.admin.ranks'
import { Route as AuthenticatedDashboardAdminReportsRouteImport } from './routes/_authenticated/dashboard.admin.reports'
import { Route as AuthenticatedDashboardAdminSecurityRouteImport } from './routes/_authenticated/dashboard.admin.security'
import { Route as AuthenticatedDashboardAdminShopRouteImport } from './routes/_authenticated/dashboard.admin.shop'
import { Route as AuthenticatedDashboardAdminStatusRouteImport } from './routes/_authenticated/dashboard.admin.status'
import { Route as AuthenticatedDashboardAdminTemplatesRouteImport } from './routes/_authenticated/dashboard.admin.templates'
import { Route as AuthenticatedDashboardAdminUsersRouteImport } from './routes/_authenticated/dashboard.admin.users'
import { Route as AuthenticatedDashboardProfileIndexRouteImport } from './routes/_authenticated/dashboard.profile.index'
import { Route as AuthenticatedDashboardProfileAdvancedRouteImport } from './routes/_authenticated/dashboard.profile.advanced'
import { Route as AuthenticatedDashboardProfileConnectionsRouteImport } from './routes/_authenticated/dashboard.profile.connections'
import { Route as AuthenticatedDashboardProfileCustomizationRouteImport } from './routes/_authenticated/dashboard.profile.customization'
import { Route as AuthenticatedDashboardProfileEffectsRouteImport } from './routes/_authenticated/dashboard.profile.effects'
import { Route as AuthenticatedDashboardProfileModulesRouteImport } from './routes/_authenticated/dashboard.profile.modules'
import { Route as AuthenticatedDashboardProfileShareRouteImport } from './routes/_authenticated/dashboard.profile.share'
import { Route as ApiPublicHooksSecurityAlertsRouteImport } from './routes/api/public/hooks/security-alerts'
import { Route as ApiPublicWebhooksDodoRouteImport } from './routes/api/public/webhooks/dodo'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RankRoute = RankRouteImport.update({
  id: '/rank',
  path: '/rank',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminRoute =
  AuthenticatedDashboardAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAnalyticsRoute =
  AuthenticatedDashboardAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBadgesRoute =
  AuthenticatedDashboardBadgesRouteImport.update({
    id: '/badges',
    path: '/badges',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardGalleryRoute =
  AuthenticatedDashboardGalleryRouteImport.update({
    id: '/gallery',
    path: '/gallery',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardGiftRoute =
  AuthenticatedDashboardGiftRouteImport.update({
    id: '/gift',
    path: '/gift',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLinksRoute =
  AuthenticatedDashboardLinksRouteImport.update({
    id: '/links',
    path: '/links',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMissionsRoute =
  AuthenticatedDashboardMissionsRouteImport.update({
    id: '/missions',
    path: '/missions',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOgRoute =
  AuthenticatedDashboardOgRouteImport.update({
    id: '/og',
    path: '/og',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPremiumRoute =
  AuthenticatedDashboardPremiumRouteImport.update({
    id: '/premium',
    path: '/premium',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfilesRoute =
  AuthenticatedDashboardProfilesRouteImport.update({
    id: '/profiles',
    path: '/profiles',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardRankRoute =
  AuthenticatedDashboardRankRouteImport.update({
    id: '/rank',
    path: '/rank',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTemplatesRoute =
  AuthenticatedDashboardTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminIndexRoute =
  AuthenticatedDashboardAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminAuditRoute =
  AuthenticatedDashboardAdminAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminBoostsRoute =
  AuthenticatedDashboardAdminBoostsRouteImport.update({
    id: '/boosts',
    path: '/boosts',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminChatRoute =
  AuthenticatedDashboardAdminChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminContentRoute =
  AuthenticatedDashboardAdminContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminEmailsRoute =
  AuthenticatedDashboardAdminEmailsRouteImport.update({
    id: '/emails',
    path: '/emails',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminIntegrationsRoute =
  AuthenticatedDashboardAdminIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminIptrackerRoute =
  AuthenticatedDashboardAdminIptrackerRouteImport.update({
    id: '/iptracker',
    path: '/iptracker',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminModerationRoute =
  AuthenticatedDashboardAdminModerationRouteImport.update({
    id: '/moderation',
    path: '/moderation',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminRanksRoute =
  AuthenticatedDashboardAdminRanksRouteImport.update({
    id: '/ranks',
    path: '/ranks',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminReportsRoute =
  AuthenticatedDashboardAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminSecurityRoute =
  AuthenticatedDashboardAdminSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminShopRoute =
  AuthenticatedDashboardAdminShopRouteImport.update({
    id: '/shop',
    path: '/shop',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminStatusRoute =
  AuthenticatedDashboardAdminStatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminTemplatesRoute =
  AuthenticatedDashboardAdminTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminUsersRoute =
  AuthenticatedDashboardAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardProfileIndexRoute =
  AuthenticatedDashboardProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardProfileRoute,
  } as any)
const AuthenticatedDashboardProfileAdvancedRoute =
  AuthenticatedDashboardProfileAdvancedRouteImport.update({
    id: '/advanced',
    path: '/advanced',
    getParentRoute: () => AuthenticatedDashboardProfileRoute,
  } as any)
const AuthenticatedDashboardProfileConnectionsRoute =
  AuthenticatedDashboardProfileConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedDashboardProfileRoute,
  } as any)
const AuthenticatedDashboardProfileCustomizationRoute =
  AuthenticatedDashboardProfileCustomizationRouteImport.update({
    id: '/customization',
    path: '/customization',
    getParentRoute: () => AuthenticatedDashboardProfileRoute,
  } as any)
const AuthenticatedDashboardProfileEffectsRoute =
  AuthenticatedDashboardProfileEffectsRouteImport.update({
    id: '/effects',
    path: '/effects',
    getParentRoute: () => AuthenticatedDashboardProfileRoute,
  } as any)
const AuthenticatedDashboardProfileModulesRoute =
  AuthenticatedDashboardProfileModulesRouteImport.update({
    id: '/modules',
    path: '/modules',
    getParentRoute: () => AuthenticatedDashboardProfileRoute,
  } as any)
const AuthenticatedDashboardProfileShareRoute =
  AuthenticatedDashboardProfileShareRouteImport.update({
    id: '/share',
    path: '/share',
    getParentRoute: () => AuthenticatedDashboardProfileRoute,
  } as any)
const ApiPublicHooksSecurityAlertsRoute =
  ApiPublicHooksSecurityAlertsRouteImport.update({
    id: '/api/public/hooks/security-alerts',
    path: '/api/public/hooks/security-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksDodoRoute = ApiPublicWebhooksDodoRouteImport.update({
  id: '/api/public/webhooks/dodo',
  path: '/api/public/webhooks/dodo',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/rank': typeof RankRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/templates': typeof TemplatesRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRouteWithChildren
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/badges': typeof AuthenticatedDashboardBadgesRoute
  '/dashboard/gallery': typeof AuthenticatedDashboardGalleryRoute
  '/dashboard/gift': typeof AuthenticatedDashboardGiftRoute
  '/dashboard/links': typeof AuthenticatedDashboardLinksRoute
  '/dashboard/missions': typeof AuthenticatedDashboardMissionsRoute
  '/dashboard/og': typeof AuthenticatedDashboardOgRoute
  '/dashboard/premium': typeof AuthenticatedDashboardPremiumRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRouteWithChildren
  '/dashboard/profiles': typeof AuthenticatedDashboardProfilesRoute
  '/dashboard/rank': typeof AuthenticatedDashboardRankRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/templates': typeof AuthenticatedDashboardTemplatesRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/admin/audit': typeof AuthenticatedDashboardAdminAuditRoute
  '/dashboard/admin/boosts': typeof AuthenticatedDashboardAdminBoostsRoute
  '/dashboard/admin/chat': typeof AuthenticatedDashboardAdminChatRoute
  '/dashboard/admin/content': typeof AuthenticatedDashboardAdminContentRoute
  '/dashboard/admin/emails': typeof AuthenticatedDashboardAdminEmailsRoute
  '/dashboard/admin/integrations': typeof AuthenticatedDashboardAdminIntegrationsRoute
  '/dashboard/admin/iptracker': typeof AuthenticatedDashboardAdminIptrackerRoute
  '/dashboard/admin/moderation': typeof AuthenticatedDashboardAdminModerationRoute
  '/dashboard/admin/ranks': typeof AuthenticatedDashboardAdminRanksRoute
  '/dashboard/admin/reports': typeof AuthenticatedDashboardAdminReportsRoute
  '/dashboard/admin/security': typeof AuthenticatedDashboardAdminSecurityRoute
  '/dashboard/admin/shop': typeof AuthenticatedDashboardAdminShopRoute
  '/dashboard/admin/status': typeof AuthenticatedDashboardAdminStatusRoute
  '/dashboard/admin/templates': typeof AuthenticatedDashboardAdminTemplatesRoute
  '/dashboard/admin/users': typeof AuthenticatedDashboardAdminUsersRoute
  '/dashboard/profile/advanced': typeof AuthenticatedDashboardProfileAdvancedRoute
  '/dashboard/profile/connections': typeof AuthenticatedDashboardProfileConnectionsRoute
  '/dashboard/profile/customization': typeof AuthenticatedDashboardProfileCustomizationRoute
  '/dashboard/profile/effects': typeof AuthenticatedDashboardProfileEffectsRoute
  '/dashboard/profile/modules': typeof AuthenticatedDashboardProfileModulesRoute
  '/dashboard/profile/share': typeof AuthenticatedDashboardProfileShareRoute
  '/api/public/hooks/security-alerts': typeof ApiPublicHooksSecurityAlertsRoute
  '/api/public/webhooks/dodo': typeof ApiPublicWebhooksDodoRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/dashboard/admin/': typeof AuthenticatedDashboardAdminIndexRoute
  '/dashboard/profile/': typeof AuthenticatedDashboardProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/rank': typeof RankRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/templates': typeof TemplatesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/badges': typeof AuthenticatedDashboardBadgesRoute
  '/dashboard/gallery': typeof AuthenticatedDashboardGalleryRoute
  '/dashboard/gift': typeof AuthenticatedDashboardGiftRoute
  '/dashboard/links': typeof AuthenticatedDashboardLinksRoute
  '/dashboard/missions': typeof AuthenticatedDashboardMissionsRoute
  '/dashboard/og': typeof AuthenticatedDashboardOgRoute
  '/dashboard/premium': typeof AuthenticatedDashboardPremiumRoute
  '/dashboard/profiles': typeof AuthenticatedDashboardProfilesRoute
  '/dashboard/rank': typeof AuthenticatedDashboardRankRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/templates': typeof AuthenticatedDashboardTemplatesRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/admin/audit': typeof AuthenticatedDashboardAdminAuditRoute
  '/dashboard/admin/boosts': typeof AuthenticatedDashboardAdminBoostsRoute
  '/dashboard/admin/chat': typeof AuthenticatedDashboardAdminChatRoute
  '/dashboard/admin/content': typeof AuthenticatedDashboardAdminContentRoute
  '/dashboard/admin/emails': typeof AuthenticatedDashboardAdminEmailsRoute
  '/dashboard/admin/integrations': typeof AuthenticatedDashboardAdminIntegrationsRoute
  '/dashboard/admin/iptracker': typeof AuthenticatedDashboardAdminIptrackerRoute
  '/dashboard/admin/moderation': typeof AuthenticatedDashboardAdminModerationRoute
  '/dashboard/admin/ranks': typeof AuthenticatedDashboardAdminRanksRoute
  '/dashboard/admin/reports': typeof AuthenticatedDashboardAdminReportsRoute
  '/dashboard/admin/security': typeof AuthenticatedDashboardAdminSecurityRoute
  '/dashboard/admin/shop': typeof AuthenticatedDashboardAdminShopRoute
  '/dashboard/admin/status': typeof AuthenticatedDashboardAdminStatusRoute
  '/dashboard/admin/templates': typeof AuthenticatedDashboardAdminTemplatesRoute
  '/dashboard/admin/users': typeof AuthenticatedDashboardAdminUsersRoute
  '/dashboard/profile/advanced': typeof AuthenticatedDashboardProfileAdvancedRoute
  '/dashboard/profile/connections': typeof AuthenticatedDashboardProfileConnectionsRoute
  '/dashboard/profile/customization': typeof AuthenticatedDashboardProfileCustomizationRoute
  '/dashboard/profile/effects': typeof AuthenticatedDashboardProfileEffectsRoute
  '/dashboard/profile/modules': typeof AuthenticatedDashboardProfileModulesRoute
  '/dashboard/profile/share': typeof AuthenticatedDashboardProfileShareRoute
  '/api/public/hooks/security-alerts': typeof ApiPublicHooksSecurityAlertsRoute
  '/api/public/webhooks/dodo': typeof ApiPublicWebhooksDodoRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminIndexRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$username': typeof UsernameRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/rank': typeof RankRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/templates': typeof TemplatesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/dashboard/admin': typeof AuthenticatedDashboardAdminRouteWithChildren
  '/_authenticated/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/_authenticated/dashboard/badges': typeof AuthenticatedDashboardBadgesRoute
  '/_authenticated/dashboard/gallery': typeof AuthenticatedDashboardGalleryRoute
  '/_authenticated/dashboard/gift': typeof AuthenticatedDashboardGiftRoute
  '/_authenticated/dashboard/links': typeof AuthenticatedDashboardLinksRoute
  '/_authenticated/dashboard/missions': typeof AuthenticatedDashboardMissionsRoute
  '/_authenticated/dashboard/og': typeof AuthenticatedDashboardOgRoute
  '/_authenticated/dashboard/premium': typeof AuthenticatedDashboardPremiumRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRouteWithChildren
  '/_authenticated/dashboard/profiles': typeof AuthenticatedDashboardProfilesRoute
  '/_authenticated/dashboard/rank': typeof AuthenticatedDashboardRankRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/templates': typeof AuthenticatedDashboardTemplatesRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/admin/audit': typeof AuthenticatedDashboardAdminAuditRoute
  '/_authenticated/dashboard/admin/boosts': typeof AuthenticatedDashboardAdminBoostsRoute
  '/_authenticated/dashboard/admin/chat': typeof AuthenticatedDashboardAdminChatRoute
  '/_authenticated/dashboard/admin/content': typeof AuthenticatedDashboardAdminContentRoute
  '/_authenticated/dashboard/admin/emails': typeof AuthenticatedDashboardAdminEmailsRoute
  '/_authenticated/dashboard/admin/integrations': typeof AuthenticatedDashboardAdminIntegrationsRoute
  '/_authenticated/dashboard/admin/iptracker': typeof AuthenticatedDashboardAdminIptrackerRoute
  '/_authenticated/dashboard/admin/moderation': typeof AuthenticatedDashboardAdminModerationRoute
  '/_authenticated/dashboard/admin/ranks': typeof AuthenticatedDashboardAdminRanksRoute
  '/_authenticated/dashboard/admin/reports': typeof AuthenticatedDashboardAdminReportsRoute
  '/_authenticated/dashboard/admin/security': typeof AuthenticatedDashboardAdminSecurityRoute
  '/_authenticated/dashboard/admin/shop': typeof AuthenticatedDashboardAdminShopRoute
  '/_authenticated/dashboard/admin/status': typeof AuthenticatedDashboardAdminStatusRoute
  '/_authenticated/dashboard/admin/templates': typeof AuthenticatedDashboardAdminTemplatesRoute
  '/_authenticated/dashboard/admin/users': typeof AuthenticatedDashboardAdminUsersRoute
  '/_authenticated/dashboard/profile/advanced': typeof AuthenticatedDashboardProfileAdvancedRoute
  '/_authenticated/dashboard/profile/connections': typeof AuthenticatedDashboardProfileConnectionsRoute
  '/_authenticated/dashboard/profile/customization': typeof AuthenticatedDashboardProfileCustomizationRoute
  '/_authenticated/dashboard/profile/effects': typeof AuthenticatedDashboardProfileEffectsRoute
  '/_authenticated/dashboard/profile/modules': typeof AuthenticatedDashboardProfileModulesRoute
  '/_authenticated/dashboard/profile/share': typeof AuthenticatedDashboardProfileShareRoute
  '/api/public/hooks/security-alerts': typeof ApiPublicHooksSecurityAlertsRoute
  '/api/public/webhooks/dodo': typeof ApiPublicWebhooksDodoRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/_authenticated/dashboard/admin/': typeof AuthenticatedDashboardAdminIndexRoute
  '/_authenticated/dashboard/profile/': typeof AuthenticatedDashboardProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/forgot-password'
    | '/login'
    | '/rank'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/status'
    | '/templates'
    | '/dashboard'
    | '/onboarding'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/badges'
    | '/dashboard/gallery'
    | '/dashboard/gift'
    | '/dashboard/links'
    | '/dashboard/missions'
    | '/dashboard/og'
    | '/dashboard/premium'
    | '/dashboard/profile'
    | '/dashboard/profiles'
    | '/dashboard/rank'
    | '/dashboard/settings'
    | '/dashboard/templates'
    | '/dashboard/'
    | '/dashboard/admin/audit'
    | '/dashboard/admin/boosts'
    | '/dashboard/admin/chat'
    | '/dashboard/admin/content'
    | '/dashboard/admin/emails'
    | '/dashboard/admin/integrations'
    | '/dashboard/admin/iptracker'
    | '/dashboard/admin/moderation'
    | '/dashboard/admin/ranks'
    | '/dashboard/admin/reports'
    | '/dashboard/admin/security'
    | '/dashboard/admin/shop'
    | '/dashboard/admin/status'
    | '/dashboard/admin/templates'
    | '/dashboard/admin/users'
    | '/dashboard/profile/advanced'
    | '/dashboard/profile/connections'
    | '/dashboard/profile/customization'
    | '/dashboard/profile/effects'
    | '/dashboard/profile/modules'
    | '/dashboard/profile/share'
    | '/api/public/hooks/security-alerts'
    | '/api/public/webhooks/dodo'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/dashboard/admin/'
    | '/dashboard/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$username'
    | '/forgot-password'
    | '/login'
    | '/rank'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/status'
    | '/templates'
    | '/onboarding'
    | '/dashboard/analytics'
    | '/dashboard/badges'
    | '/dashboard/gallery'
    | '/dashboard/gift'
    | '/dashboard/links'
    | '/dashboard/missions'
    | '/dashboard/og'
    | '/dashboard/premium'
    | '/dashboard/profiles'
    | '/dashboard/rank'
    | '/dashboard/settings'
    | '/dashboard/templates'
    | '/dashboard'
    | '/dashboard/admin/audit'
    | '/dashboard/admin/boosts'
    | '/dashboard/admin/chat'
    | '/dashboard/admin/content'
    | '/dashboard/admin/emails'
    | '/dashboard/admin/integrations'
    | '/dashboard/admin/iptracker'
    | '/dashboard/admin/moderation'
    | '/dashboard/admin/ranks'
    | '/dashboard/admin/reports'
    | '/dashboard/admin/security'
    | '/dashboard/admin/shop'
    | '/dashboard/admin/status'
    | '/dashboard/admin/templates'
    | '/dashboard/admin/users'
    | '/dashboard/profile/advanced'
    | '/dashboard/profile/connections'
    | '/dashboard/profile/customization'
    | '/dashboard/profile/effects'
    | '/dashboard/profile/modules'
    | '/dashboard/profile/share'
    | '/api/public/hooks/security-alerts'
    | '/api/public/webhooks/dodo'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/dashboard/admin'
    | '/dashboard/profile'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$username'
    | '/forgot-password'
    | '/login'
    | '/rank'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/status'
    | '/templates'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/dashboard/admin'
    | '/_authenticated/dashboard/analytics'
    | '/_authenticated/dashboard/badges'
    | '/_authenticated/dashboard/gallery'
    | '/_authenticated/dashboard/gift'
    | '/_authenticated/dashboard/links'
    | '/_authenticated/dashboard/missions'
    | '/_authenticated/dashboard/og'
    | '/_authenticated/dashboard/premium'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/profiles'
    | '/_authenticated/dashboard/rank'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/templates'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/admin/audit'
    | '/_authenticated/dashboard/admin/boosts'
    | '/_authenticated/dashboard/admin/chat'
    | '/_authenticated/dashboard/admin/content'
    | '/_authenticated/dashboard/admin/emails'
    | '/_authenticated/dashboard/admin/integrations'
    | '/_authenticated/dashboard/admin/iptracker'
    | '/_authenticated/dashboard/admin/moderation'
    | '/_authenticated/dashboard/admin/ranks'
    | '/_authenticated/dashboard/admin/reports'
    | '/_authenticated/dashboard/admin/security'
    | '/_authenticated/dashboard/admin/shop'
    | '/_authenticated/dashboard/admin/status'
    | '/_authenticated/dashboard/admin/templates'
    | '/_authenticated/dashboard/admin/users'
    | '/_authenticated/dashboard/profile/advanced'
    | '/_authenticated/dashboard/profile/connections'
    | '/_authenticated/dashboard/profile/customization'
    | '/_authenticated/dashboard/profile/effects'
    | '/_authenticated/dashboard/profile/modules'
    | '/_authenticated/dashboard/profile/share'
    | '/api/public/hooks/security-alerts'
    | '/api/public/webhooks/dodo'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/_authenticated/dashboard/admin/'
    | '/_authenticated/dashboard/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  UsernameRoute: typeof UsernameRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RankRoute: typeof RankRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatusRoute: typeof StatusRoute
  TemplatesRoute: typeof TemplatesRoute
  ApiPublicHooksSecurityAlertsRoute: typeof ApiPublicHooksSecurityAlertsRoute
  ApiPublicWebhooksDodoRoute: typeof ApiPublicWebhooksDodoRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rank': {
      id: '/rank'
      path: '/rank'
      fullPath: '/rank'
      preLoaderRoute: typeof RankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin': {
      id: '/_authenticated/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/analytics': {
      id: '/_authenticated/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof AuthenticatedDashboardAnalyticsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/badges': {
      id: '/_authenticated/dashboard/badges'
      path: '/badges'
      fullPath: '/dashboard/badges'
      preLoaderRoute: typeof AuthenticatedDashboardBadgesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/gallery': {
      id: '/_authenticated/dashboard/gallery'
      path: '/gallery'
      fullPath: '/dashboard/gallery'
      preLoaderRoute: typeof AuthenticatedDashboardGalleryRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/gift': {
      id: '/_authenticated/dashboard/gift'
      path: '/gift'
      fullPath: '/dashboard/gift'
      preLoaderRoute: typeof AuthenticatedDashboardGiftRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/links': {
      id: '/_authenticated/dashboard/links'
      path: '/links'
      fullPath: '/dashboard/links'
      preLoaderRoute: typeof AuthenticatedDashboardLinksRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/missions': {
      id: '/_authenticated/dashboard/missions'
      path: '/missions'
      fullPath: '/dashboard/missions'
      preLoaderRoute: typeof AuthenticatedDashboardMissionsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/og': {
      id: '/_authenticated/dashboard/og'
      path: '/og'
      fullPath: '/dashboard/og'
      preLoaderRoute: typeof AuthenticatedDashboardOgRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/premium': {
      id: '/_authenticated/dashboard/premium'
      path: '/premium'
      fullPath: '/dashboard/premium'
      preLoaderRoute: typeof AuthenticatedDashboardPremiumRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profiles': {
      id: '/_authenticated/dashboard/profiles'
      path: '/profiles'
      fullPath: '/dashboard/profiles'
      preLoaderRoute: typeof AuthenticatedDashboardProfilesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/rank': {
      id: '/_authenticated/dashboard/rank'
      path: '/rank'
      fullPath: '/dashboard/rank'
      preLoaderRoute: typeof AuthenticatedDashboardRankRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/templates': {
      id: '/_authenticated/dashboard/templates'
      path: '/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof AuthenticatedDashboardTemplatesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin/': {
      id: '/_authenticated/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof AuthenticatedDashboardAdminIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/audit': {
      id: '/_authenticated/dashboard/admin/audit'
      path: '/audit'
      fullPath: '/dashboard/admin/audit'
      preLoaderRoute: typeof AuthenticatedDashboardAdminAuditRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/boosts': {
      id: '/_authenticated/dashboard/admin/boosts'
      path: '/boosts'
      fullPath: '/dashboard/admin/boosts'
      preLoaderRoute: typeof AuthenticatedDashboardAdminBoostsRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/chat': {
      id: '/_authenticated/dashboard/admin/chat'
      path: '/chat'
      fullPath: '/dashboard/admin/chat'
      preLoaderRoute: typeof AuthenticatedDashboardAdminChatRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/content': {
      id: '/_authenticated/dashboard/admin/content'
      path: '/content'
      fullPath: '/dashboard/admin/content'
      preLoaderRoute: typeof AuthenticatedDashboardAdminContentRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/emails': {
      id: '/_authenticated/dashboard/admin/emails'
      path: '/emails'
      fullPath: '/dashboard/admin/emails'
      preLoaderRoute: typeof AuthenticatedDashboardAdminEmailsRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/integrations': {
      id: '/_authenticated/dashboard/admin/integrations'
      path: '/integrations'
      fullPath: '/dashboard/admin/integrations'
      preLoaderRoute: typeof AuthenticatedDashboardAdminIntegrationsRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/iptracker': {
      id: '/_authenticated/dashboard/admin/iptracker'
      path: '/iptracker'
      fullPath: '/dashboard/admin/iptracker'
      preLoaderRoute: typeof AuthenticatedDashboardAdminIptrackerRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/moderation': {
      id: '/_authenticated/dashboard/admin/moderation'
      path: '/moderation'
      fullPath: '/dashboard/admin/moderation'
      preLoaderRoute: typeof AuthenticatedDashboardAdminModerationRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/ranks': {
      id: '/_authenticated/dashboard/admin/ranks'
      path: '/ranks'
      fullPath: '/dashboard/admin/ranks'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRanksRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/reports': {
      id: '/_authenticated/dashboard/admin/reports'
      path: '/reports'
      fullPath: '/dashboard/admin/reports'
      preLoaderRoute: typeof AuthenticatedDashboardAdminReportsRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/security': {
      id: '/_authenticated/dashboard/admin/security'
      path: '/security'
      fullPath: '/dashboard/admin/security'
      preLoaderRoute: typeof AuthenticatedDashboardAdminSecurityRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/shop': {
      id: '/_authenticated/dashboard/admin/shop'
      path: '/shop'
      fullPath: '/dashboard/admin/shop'
      preLoaderRoute: typeof AuthenticatedDashboardAdminShopRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/status': {
      id: '/_authenticated/dashboard/admin/status'
      path: '/status'
      fullPath: '/dashboard/admin/status'
      preLoaderRoute: typeof AuthenticatedDashboardAdminStatusRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/templates': {
      id: '/_authenticated/dashboard/admin/templates'
      path: '/templates'
      fullPath: '/dashboard/admin/templates'
      preLoaderRoute: typeof AuthenticatedDashboardAdminTemplatesRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/users': {
      id: '/_authenticated/dashboard/admin/users'
      path: '/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof AuthenticatedDashboardAdminUsersRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/profile/': {
      id: '/_authenticated/dashboard/profile/'
      path: '/'
      fullPath: '/dashboard/profile/'
      preLoaderRoute: typeof AuthenticatedDashboardProfileIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardProfileRoute
    }
    '/_authenticated/dashboard/profile/advanced': {
      id: '/_authenticated/dashboard/profile/advanced'
      path: '/advanced'
      fullPath: '/dashboard/profile/advanced'
      preLoaderRoute: typeof AuthenticatedDashboardProfileAdvancedRouteImport
      parentRoute: typeof AuthenticatedDashboardProfileRoute
    }
    '/_authenticated/dashboard/profile/connections': {
      id: '/_authenticated/dashboard/profile/connections'
      path: '/connections'
      fullPath: '/dashboard/profile/connections'
      preLoaderRoute: typeof AuthenticatedDashboardProfileConnectionsRouteImport
      parentRoute: typeof AuthenticatedDashboardProfileRoute
    }
    '/_authenticated/dashboard/profile/customization': {
      id: '/_authenticated/dashboard/profile/customization'
      path: '/customization'
      fullPath: '/dashboard/profile/customization'
      preLoaderRoute: typeof AuthenticatedDashboardProfileCustomizationRouteImport
      parentRoute: typeof AuthenticatedDashboardProfileRoute
    }
    '/_authenticated/dashboard/profile/effects': {
      id: '/_authenticated/dashboard/profile/effects'
      path: '/effects'
      fullPath: '/dashboard/profile/effects'
      preLoaderRoute: typeof AuthenticatedDashboardProfileEffectsRouteImport
      parentRoute: typeof AuthenticatedDashboardProfileRoute
    }
    '/_authenticated/dashboard/profile/modules': {
      id: '/_authenticated/dashboard/profile/modules'
      path: '/modules'
      fullPath: '/dashboard/profile/modules'
      preLoaderRoute: typeof AuthenticatedDashboardProfileModulesRouteImport
      parentRoute: typeof AuthenticatedDashboardProfileRoute
    }
    '/_authenticated/dashboard/profile/share': {
      id: '/_authenticated/dashboard/profile/share'
      path: '/share'
      fullPath: '/dashboard/profile/share'
      preLoaderRoute: typeof AuthenticatedDashboardProfileShareRouteImport
      parentRoute: typeof AuthenticatedDashboardProfileRoute
    }
    '/api/public/hooks/security-alerts': {
      id: '/api/public/hooks/security-alerts'
      path: '/api/public/hooks/security-alerts'
      fullPath: '/api/public/hooks/security-alerts'
      preLoaderRoute: typeof ApiPublicHooksSecurityAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/dodo': {
      id: '/api/public/webhooks/dodo'
      path: '/api/public/webhooks/dodo'
      fullPath: '/api/public/webhooks/dodo'
      preLoaderRoute: typeof ApiPublicWebhooksDodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDashboardAdminRouteChildren {
  AuthenticatedDashboardAdminAuditRoute: typeof AuthenticatedDashboardAdminAuditRoute
  AuthenticatedDashboardAdminBoostsRoute: typeof AuthenticatedDashboardAdminBoostsRoute
  AuthenticatedDashboardAdminChatRoute: typeof AuthenticatedDashboardAdminChatRoute
  AuthenticatedDashboardAdminContentRoute: typeof AuthenticatedDashboardAdminContentRoute
  AuthenticatedDashboardAdminEmailsRoute: typeof AuthenticatedDashboardAdminEmailsRoute
  AuthenticatedDashboardAdminIntegrationsRoute: typeof AuthenticatedDashboardAdminIntegrationsRoute
  AuthenticatedDashboardAdminIptrackerRoute: typeof AuthenticatedDashboardAdminIptrackerRoute
  AuthenticatedDashboardAdminModerationRoute: typeof AuthenticatedDashboardAdminModerationRoute
  AuthenticatedDashboardAdminRanksRoute: typeof AuthenticatedDashboardAdminRanksRoute
  AuthenticatedDashboardAdminReportsRoute: typeof AuthenticatedDashboardAdminReportsRoute
  AuthenticatedDashboardAdminSecurityRoute: typeof AuthenticatedDashboardAdminSecurityRoute
  AuthenticatedDashboardAdminShopRoute: typeof AuthenticatedDashboardAdminShopRoute
  AuthenticatedDashboardAdminStatusRoute: typeof AuthenticatedDashboardAdminStatusRoute
  AuthenticatedDashboardAdminTemplatesRoute: typeof AuthenticatedDashboardAdminTemplatesRoute
  AuthenticatedDashboardAdminUsersRoute: typeof AuthenticatedDashboardAdminUsersRoute
  AuthenticatedDashboardAdminIndexRoute: typeof AuthenticatedDashboardAdminIndexRoute
}

const AuthenticatedDashboardAdminRouteChildren: AuthenticatedDashboardAdminRouteChildren =
  {
    AuthenticatedDashboardAdminAuditRoute:
      AuthenticatedDashboardAdminAuditRoute,
    AuthenticatedDashboardAdminBoostsRoute:
      AuthenticatedDashboardAdminBoostsRoute,
    AuthenticatedDashboardAdminChatRoute: AuthenticatedDashboardAdminChatRoute,
    AuthenticatedDashboardAdminContentRoute:
      AuthenticatedDashboardAdminContentRoute,
    AuthenticatedDashboardAdminEmailsRoute:
      AuthenticatedDashboardAdminEmailsRoute,
    AuthenticatedDashboardAdminIntegrationsRoute:
      AuthenticatedDashboardAdminIntegrationsRoute,
    AuthenticatedDashboardAdminIptrackerRoute:
      AuthenticatedDashboardAdminIptrackerRoute,
    AuthenticatedDashboardAdminModerationRoute:
      AuthenticatedDashboardAdminModerationRoute,
    AuthenticatedDashboardAdminRanksRoute:
      AuthenticatedDashboardAdminRanksRoute,
    AuthenticatedDashboardAdminReportsRoute:
      AuthenticatedDashboardAdminReportsRoute,
    AuthenticatedDashboardAdminSecurityRoute:
      AuthenticatedDashboardAdminSecurityRoute,
    AuthenticatedDashboardAdminShopRoute: AuthenticatedDashboardAdminShopRoute,
    AuthenticatedDashboardAdminStatusRoute:
      AuthenticatedDashboardAdminStatusRoute,
    AuthenticatedDashboardAdminTemplatesRoute:
      AuthenticatedDashboardAdminTemplatesRoute,
    AuthenticatedDashboardAdminUsersRoute:
      AuthenticatedDashboardAdminUsersRoute,
    AuthenticatedDashboardAdminIndexRoute:
      AuthenticatedDashboardAdminIndexRoute,
  }

const AuthenticatedDashboardAdminRouteWithChildren =
  AuthenticatedDashboardAdminRoute._addFileChildren(
    AuthenticatedDashboardAdminRouteChildren,
  )

interface AuthenticatedDashboardProfileRouteChildren {
  AuthenticatedDashboardProfileAdvancedRoute: typeof AuthenticatedDashboardProfileAdvancedRoute
  AuthenticatedDashboardProfileConnectionsRoute: typeof AuthenticatedDashboardProfileConnectionsRoute
  AuthenticatedDashboardProfileCustomizationRoute: typeof AuthenticatedDashboardProfileCustomizationRoute
  AuthenticatedDashboardProfileEffectsRoute: typeof AuthenticatedDashboardProfileEffectsRoute
  AuthenticatedDashboardProfileModulesRoute: typeof AuthenticatedDashboardProfileModulesRoute
  AuthenticatedDashboardProfileShareRoute: typeof AuthenticatedDashboardProfileShareRoute
  AuthenticatedDashboardProfileIndexRoute: typeof AuthenticatedDashboardProfileIndexRoute
}

const AuthenticatedDashboardProfileRouteChildren: AuthenticatedDashboardProfileRouteChildren =
  {
    AuthenticatedDashboardProfileAdvancedRoute:
      AuthenticatedDashboardProfileAdvancedRoute,
    AuthenticatedDashboardProfileConnectionsRoute:
      AuthenticatedDashboardProfileConnectionsRoute,
    AuthenticatedDashboardProfileCustomizationRoute:
      AuthenticatedDashboardProfileCustomizationRoute,
    AuthenticatedDashboardProfileEffectsRoute:
      AuthenticatedDashboardProfileEffectsRoute,
    AuthenticatedDashboardProfileModulesRoute:
      AuthenticatedDashboardProfileModulesRoute,
    AuthenticatedDashboardProfileShareRoute:
      AuthenticatedDashboardProfileShareRoute,
    AuthenticatedDashboardProfileIndexRoute:
      AuthenticatedDashboardProfileIndexRoute,
  }

const AuthenticatedDashboardProfileRouteWithChildren =
  AuthenticatedDashboardProfileRoute._addFileChildren(
    AuthenticatedDashboardProfileRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAdminRoute: typeof AuthenticatedDashboardAdminRouteWithChildren
  AuthenticatedDashboardAnalyticsRoute: typeof AuthenticatedDashboardAnalyticsRoute
  AuthenticatedDashboardBadgesRoute: typeof AuthenticatedDashboardBadgesRoute
  AuthenticatedDashboardGalleryRoute: typeof AuthenticatedDashboardGalleryRoute
  AuthenticatedDashboardGiftRoute: typeof AuthenticatedDashboardGiftRoute
  AuthenticatedDashboardLinksRoute: typeof AuthenticatedDashboardLinksRoute
  AuthenticatedDashboardMissionsRoute: typeof AuthenticatedDashboardMissionsRoute
  AuthenticatedDashboardOgRoute: typeof AuthenticatedDashboardOgRoute
  AuthenticatedDashboardPremiumRoute: typeof AuthenticatedDashboardPremiumRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRouteWithChildren
  AuthenticatedDashboardProfilesRoute: typeof AuthenticatedDashboardProfilesRoute
  AuthenticatedDashboardRankRoute: typeof AuthenticatedDashboardRankRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardTemplatesRoute: typeof AuthenticatedDashboardTemplatesRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAdminRoute:
      AuthenticatedDashboardAdminRouteWithChildren,
    AuthenticatedDashboardAnalyticsRoute: AuthenticatedDashboardAnalyticsRoute,
    AuthenticatedDashboardBadgesRoute: AuthenticatedDashboardBadgesRoute,
    AuthenticatedDashboardGalleryRoute: AuthenticatedDashboardGalleryRoute,
    AuthenticatedDashboardGiftRoute: AuthenticatedDashboardGiftRoute,
    AuthenticatedDashboardLinksRoute: AuthenticatedDashboardLinksRoute,
    AuthenticatedDashboardMissionsRoute: AuthenticatedDashboardMissionsRoute,
    AuthenticatedDashboardOgRoute: AuthenticatedDashboardOgRoute,
    AuthenticatedDashboardPremiumRoute: AuthenticatedDashboardPremiumRoute,
    AuthenticatedDashboardProfileRoute:
      AuthenticatedDashboardProfileRouteWithChildren,
    AuthenticatedDashboardProfilesRoute: AuthenticatedDashboardProfilesRoute,
    AuthenticatedDashboardRankRoute: AuthenticatedDashboardRankRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardTemplatesRoute: AuthenticatedDashboardTemplatesRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  UsernameRoute: UsernameRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RankRoute: RankRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatusRoute: StatusRoute,
  TemplatesRoute: TemplatesRoute,
  ApiPublicHooksSecurityAlertsRoute: ApiPublicHooksSecurityAlertsRoute,
  ApiPublicWebhooksDodoRoute: ApiPublicWebhooksDodoRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
